/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 212 "/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h"
typedef unsigned long size_t;
#line 131 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
#line 132 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
#line 139 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __time_t;
#line 141 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __suseconds_t;
#line 44 "/usr/include/stdio.h"
struct _IO_FILE;
#line 44
struct _IO_FILE;
#line 48 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 154 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 160 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 245 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 75 "/usr/include/time.h"
typedef __time_t time_t;
#line 30 "/usr/include/x86_64-linux-gnu/bits/time.h"
struct timeval {
   __time_t tv_sec ;
   __suseconds_t tv_usec ;
};
#line 133 "/usr/include/time.h"
struct tm {
   int tm_sec ;
   int tm_min ;
   int tm_hour ;
   int tm_mday ;
   int tm_mon ;
   int tm_year ;
   int tm_wday ;
   int tm_yday ;
   int tm_isdst ;
   long tm_gmtoff ;
   char const   *tm_zone ;
};
#line 51 "/usr/include/stdint.h"
typedef unsigned int uint32_t;
#line 23 "/usr/include/asm-generic/int-ll64.h"
typedef unsigned short __u16;
#line 25 "/usr/include/asm-generic/int-ll64.h"
typedef int __s32;
#line 22 "/usr/include/linux/input.h"
struct input_event {
   struct timeval time ;
   __u16 type ;
   __u16 code ;
   __s32 value ;
};
#line 39 "/usr/include/linux/input.h"
struct input_id {
   __u16 bustype ;
   __u16 vendor ;
   __u16 product ;
   __u16 version ;
};
#line 124 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __dev_t;
#line 125 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __uid_t;
#line 126 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __gid_t;
#line 127 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __ino_t;
#line 129 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __mode_t;
#line 130 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __nlink_t;
#line 153 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __blksize_t;
#line 158 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __blkcnt_t;
#line 175 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __syscall_slong_t;
#line 120 "/usr/include/time.h"
struct timespec {
   __time_t tv_sec ;
   __syscall_slong_t tv_nsec ;
};
#line 46 "/usr/include/x86_64-linux-gnu/bits/stat.h"
struct stat {
   __dev_t st_dev ;
   __ino_t st_ino ;
   __nlink_t st_nlink ;
   __mode_t st_mode ;
   __uid_t st_uid ;
   __gid_t st_gid ;
   int __pad0 ;
   __dev_t st_rdev ;
   __off_t st_size ;
   __blksize_t st_blksize ;
   __blkcnt_t st_blocks ;
   struct timespec st_atim ;
   struct timespec st_mtim ;
   struct timespec st_ctim ;
   __syscall_slong_t __glibc_reserved[3] ;
};
#line 170 "/usr/include/stdio.h"
extern struct _IO_FILE *stderr ;
#line 356
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
#line 362
extern int printf(char const   * __restrict  __format  , ...) ;
#line 386
extern  __attribute__((__nothrow__)) int snprintf(char * __restrict  __s , size_t __maxlen ,
                                                  char const   * __restrict  __format 
                                                  , ...) ;
#line 413 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) char *( __attribute__((__leaf__)) strerror)(int __errnum ) ;
#line 205 "/usr/include/time.h"
extern  __attribute__((__nothrow__)) size_t ( __attribute__((__leaf__)) strftime)(char * __restrict  __s ,
                                                                                  size_t __maxsize ,
                                                                                  char const   * __restrict  __format ,
                                                                                  struct tm  const  * __restrict  __tp ) ;
#line 243
extern  __attribute__((__nothrow__)) struct tm *( __attribute__((__leaf__)) localtime)(time_t const   *__timer ) ;
#line 50 "/usr/include/x86_64-linux-gnu/bits/errno.h"
extern  __attribute__((__nothrow__)) int *( __attribute__((__leaf__)) __errno_location)(void)  __attribute__((__const__)) ;
#line 146 "/usr/include/fcntl.h"
extern int ( __attribute__((__nonnull__(1))) open)(char const   *__file , int __oflag 
                                                   , ...) ;
#line 41 "/usr/include/x86_64-linux-gnu/sys/ioctl.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) ioctl)(int __fd ,
                                                                            unsigned long __request 
                                                                            , ...) ;
#line 11 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.h"
char *EV_NAME[32] ;
#line 12
int EV_TYPE_MAX[32] ;
#line 13
char **EV_TYPE_NAME[32] ;
#line 14
char *BUS_NAME[29] ;
#line 16 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.h"
__inline static int test_bit(int nr , uint32_t *addr ) 
{ 
  uint32_t mask ;

  {
#line 20
  addr += nr >> 5;
#line 21
  mask = (uint32_t )(1 << (nr & 31));
#line 22
  return ((mask & *addr) != 0U);
}
}
#line 27
int device_open(int nr , int verbose ) ;
#line 28
void device_info(int fd ) ;
#line 29
void print_event(struct input_event *event ) ;
#line 14 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.c"
char *EV_NAME[32]  = 
#line 14 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.c"
  {      (char *)"EV_SYN",      (char *)"EV_KEY",      (char *)"EV_REL",      (char *)"EV_ABS", 
        (char *)"EV_MSC",      (char *)"EV_SW",      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)"EV_LED",      (char *)"EV_SND",      (char *)0, 
        (char *)"EV_REP",      (char *)"EV_FF",      (char *)"EV_PWR",      (char *)"EV_FF_STATUS"};
#line 18 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.c"
static char *REL_NAME[16]  = 
#line 18
  {      (char *)"REL_X",      (char *)"REL_Y",      (char *)"REL_Z",      (char *)"REL_RX", 
        (char *)"REL_RY",      (char *)"REL_RZ",      (char *)"REL_HWHEEL",      (char *)"REL_DIAL", 
        (char *)"REL_WHEEL",      (char *)"REL_MISC"};
#line 22 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.c"
static char *ABS_NAME[64]  = 
#line 22
  {      (char *)"ABS_X",      (char *)"ABS_Y",      (char *)"ABS_Z",      (char *)"ABS_RX", 
        (char *)"ABS_RY",      (char *)"ABS_RZ",      (char *)"ABS_THROTTLE",      (char *)"ABS_RUDDER", 
        (char *)"ABS_WHEEL",      (char *)"ABS_GAS",      (char *)"ABS_BRAKE",      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)"ABS_HAT0X",      (char *)"ABS_HAT0Y",      (char *)"ABS_HAT1X",      (char *)"ABS_HAT1Y", 
        (char *)"ABS_HAT2X",      (char *)"ABS_HAT2Y",      (char *)"ABS_HAT3X",      (char *)"ABS_HAT3Y", 
        (char *)"ABS_PRESSURE",      (char *)"ABS_DISTANCE",      (char *)"ABS_TILT_X",      (char *)"ABS_TILT_Y", 
        (char *)"ABS_TOOL_WIDTH",      (char *)0,      (char *)0,      (char *)0, 
        (char *)"ABS_VOLUME",      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)"ABS_MISC",      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)"ABS_MT_SLOT", 
        (char *)"ABS_MT_TOUCH_MAJOR",      (char *)"ABS_MT_TOUCH_MINOR",      (char *)"ABS_MT_WIDTH_MAJOR",      (char *)"ABS_MT_WIDTH_MINOR", 
        (char *)"ABS_MT_ORIENTATION",      (char *)"ABS_MT_POSITION_X",      (char *)"ABS_MT_POSITION_Y",      (char *)"ABS_MT_TOOL_TYPE", 
        (char *)"ABS_MT_BLOB_ID",      (char *)"ABS_MT_TRACKING_ID",      (char *)"ABS_MT_PRESSURE",      (char *)"ABS_MT_DISTANCE", 
        (char *)"ABS_MT_TOOL_X",      (char *)"ABS_MT_TOOL_Y"};
#line 26 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.c"
static char *MSC_NAME[8]  = {      (char *)"MSC_SERIAL",      (char *)"MSC_PULSELED",      (char *)"MSC_GESTURE",      (char *)"MSC_RAW", 
        (char *)"MSC_SCAN",      (char *)"MSC_TIMESTAMP"};
#line 30 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.c"
static char *LED_NAME[16]  = 
#line 30
  {      (char *)"LED_NUML",      (char *)"LED_CAPSL",      (char *)"LED_SCROLLL",      (char *)"LED_COMPOSE", 
        (char *)"LED_KANA",      (char *)"LED_SLEEP",      (char *)"LED_SUSPEND",      (char *)"LED_MUTE", 
        (char *)"LED_MISC",      (char *)"LED_MAIL",      (char *)"LED_CHARGING"};
#line 34 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.c"
static char *SND_NAME[8]  = {      (char *)"SND_CLICK",      (char *)"SND_BELL",      (char *)"SND_TONE"};
#line 42 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.c"
static char *REP_NAME[2]  = {      (char *)"REP_DELAY",      (char *)"REP_PERIOD"};
#line 46 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.c"
static char *KEY_NAME[768]  = 
#line 46
  {      (char *)"KEY_RESERVED",      (char *)"KEY_ESC",      (char *)"KEY_1",      (char *)"KEY_2", 
        (char *)"KEY_3",      (char *)"KEY_4",      (char *)"KEY_5",      (char *)"KEY_6", 
        (char *)"KEY_7",      (char *)"KEY_8",      (char *)"KEY_9",      (char *)"KEY_0", 
        (char *)"KEY_MINUS",      (char *)"KEY_EQUAL",      (char *)"KEY_BACKSPACE",      (char *)"KEY_TAB", 
        (char *)"KEY_Q",      (char *)"KEY_W",      (char *)"KEY_E",      (char *)"KEY_R", 
        (char *)"KEY_T",      (char *)"KEY_Y",      (char *)"KEY_U",      (char *)"KEY_I", 
        (char *)"KEY_O",      (char *)"KEY_P",      (char *)"KEY_LEFTBRACE",      (char *)"KEY_RIGHTBRACE", 
        (char *)"KEY_ENTER",      (char *)"KEY_LEFTCTRL",      (char *)"KEY_A",      (char *)"KEY_S", 
        (char *)"KEY_D",      (char *)"KEY_F",      (char *)"KEY_G",      (char *)"KEY_H", 
        (char *)"KEY_J",      (char *)"KEY_K",      (char *)"KEY_L",      (char *)"KEY_SEMICOLON", 
        (char *)"KEY_APOSTROPHE",      (char *)"KEY_GRAVE",      (char *)"KEY_LEFTSHIFT",      (char *)"KEY_BACKSLASH", 
        (char *)"KEY_Z",      (char *)"KEY_X",      (char *)"KEY_C",      (char *)"KEY_V", 
        (char *)"KEY_B",      (char *)"KEY_N",      (char *)"KEY_M",      (char *)"KEY_COMMA", 
        (char *)"KEY_DOT",      (char *)"KEY_SLASH",      (char *)"KEY_RIGHTSHIFT",      (char *)"KEY_KPASTERISK", 
        (char *)"KEY_LEFTALT",      (char *)"KEY_SPACE",      (char *)"KEY_CAPSLOCK",      (char *)"KEY_F1", 
        (char *)"KEY_F2",      (char *)"KEY_F3",      (char *)"KEY_F4",      (char *)"KEY_F5", 
        (char *)"KEY_F6",      (char *)"KEY_F7",      (char *)"KEY_F8",      (char *)"KEY_F9", 
        (char *)"KEY_F10",      (char *)"KEY_NUMLOCK",      (char *)"KEY_SCROLLLOCK",      (char *)"KEY_KP7", 
        (char *)"KEY_KP8",      (char *)"KEY_KP9",      (char *)"KEY_KPMINUS",      (char *)"KEY_KP4", 
        (char *)"KEY_KP5",      (char *)"KEY_KP6",      (char *)"KEY_KPPLUS",      (char *)"KEY_KP1", 
        (char *)"KEY_KP2",      (char *)"KEY_KP3",      (char *)"KEY_KP0",      (char *)"KEY_KPDOT", 
        (char *)0,      (char *)"KEY_ZENKAKUHANKAKU",      (char *)"KEY_102ND",      (char *)"KEY_F11", 
        (char *)"KEY_F12",      (char *)"KEY_RO",      (char *)"KEY_KATAKANA",      (char *)"KEY_HIRAGANA", 
        (char *)"KEY_HENKAN",      (char *)"KEY_KATAKANAHIRAGANA",      (char *)"KEY_MUHENKAN",      (char *)"KEY_KPJPCOMMA", 
        (char *)"KEY_KPENTER",      (char *)"KEY_RIGHTCTRL",      (char *)"KEY_KPSLASH",      (char *)"KEY_SYSRQ", 
        (char *)"KEY_RIGHTALT",      (char *)"KEY_LINEFEED",      (char *)"KEY_HOME",      (char *)"KEY_UP", 
        (char *)"KEY_PAGEUP",      (char *)"KEY_LEFT",      (char *)"KEY_RIGHT",      (char *)"KEY_END", 
        (char *)"KEY_DOWN",      (char *)"KEY_PAGEDOWN",      (char *)"KEY_INSERT",      (char *)"KEY_DELETE", 
        (char *)"KEY_MACRO",      (char *)"KEY_MIN_INTERESTING",      (char *)"KEY_VOLUMEDOWN",      (char *)"KEY_VOLUMEUP", 
        (char *)"KEY_POWER",      (char *)"KEY_KPEQUAL",      (char *)"KEY_KPPLUSMINUS",      (char *)"KEY_PAUSE", 
        (char *)"KEY_SCALE",      (char *)"KEY_KPCOMMA",      (char *)"KEY_HANGUEL",      (char *)"KEY_HANJA", 
        (char *)"KEY_YEN",      (char *)"KEY_LEFTMETA",      (char *)"KEY_RIGHTMETA",      (char *)"KEY_COMPOSE", 
        (char *)"KEY_STOP",      (char *)"KEY_AGAIN",      (char *)"KEY_PROPS",      (char *)"KEY_UNDO", 
        (char *)"KEY_FRONT",      (char *)"KEY_COPY",      (char *)"KEY_OPEN",      (char *)"KEY_PASTE", 
        (char *)"KEY_FIND",      (char *)"KEY_CUT",      (char *)"KEY_HELP",      (char *)"KEY_MENU", 
        (char *)"KEY_CALC",      (char *)"KEY_SETUP",      (char *)"KEY_SLEEP",      (char *)"KEY_WAKEUP", 
        (char *)"KEY_FILE",      (char *)"KEY_SENDFILE",      (char *)"KEY_DELETEFILE",      (char *)"KEY_XFER", 
        (char *)"KEY_PROG1",      (char *)"KEY_PROG2",      (char *)"KEY_WWW",      (char *)"KEY_MSDOS", 
        (char *)"KEY_SCREENLOCK",      (char *)"KEY_DIRECTION",      (char *)"KEY_CYCLEWINDOWS",      (char *)"KEY_MAIL", 
        (char *)"KEY_BOOKMARKS",      (char *)"KEY_COMPUTER",      (char *)"KEY_BACK",      (char *)"KEY_FORWARD", 
        (char *)"KEY_CLOSECD",      (char *)"KEY_EJECTCD",      (char *)"KEY_EJECTCLOSECD",      (char *)"KEY_NEXTSONG", 
        (char *)"KEY_PLAYPAUSE",      (char *)"KEY_PREVIOUSSONG",      (char *)"KEY_STOPCD",      (char *)"KEY_RECORD", 
        (char *)"KEY_REWIND",      (char *)"KEY_PHONE",      (char *)"KEY_ISO",      (char *)"KEY_CONFIG", 
        (char *)"KEY_HOMEPAGE",      (char *)"KEY_REFRESH",      (char *)"KEY_EXIT",      (char *)"KEY_MOVE", 
        (char *)"KEY_EDIT",      (char *)"KEY_SCROLLUP",      (char *)"KEY_SCROLLDOWN",      (char *)"KEY_KPLEFTPAREN", 
        (char *)"KEY_KPRIGHTPAREN",      (char *)"KEY_NEW",      (char *)"KEY_REDO",      (char *)"KEY_F13", 
        (char *)"KEY_F14",      (char *)"KEY_F15",      (char *)"KEY_F16",      (char *)"KEY_F17", 
        (char *)"KEY_F18",      (char *)"KEY_F19",      (char *)"KEY_F20",      (char *)"KEY_F21", 
        (char *)"KEY_F22",      (char *)"KEY_F23",      (char *)"KEY_F24",      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)"KEY_PLAYCD",      (char *)"KEY_PAUSECD",      (char *)"KEY_PROG3",      (char *)"KEY_PROG4", 
        (char *)"KEY_DASHBOARD",      (char *)"KEY_SUSPEND",      (char *)"KEY_CLOSE",      (char *)"KEY_PLAY", 
        (char *)"KEY_FASTFORWARD",      (char *)"KEY_BASSBOOST",      (char *)"KEY_PRINT",      (char *)"KEY_HP", 
        (char *)"KEY_CAMERA",      (char *)"KEY_SOUND",      (char *)"KEY_QUESTION",      (char *)"KEY_EMAIL", 
        (char *)"KEY_CHAT",      (char *)"KEY_SEARCH",      (char *)"KEY_CONNECT",      (char *)"KEY_FINANCE", 
        (char *)"KEY_SPORT",      (char *)"KEY_SHOP",      (char *)"KEY_ALTERASE",      (char *)"KEY_CANCEL", 
        (char *)"KEY_BRIGHTNESSDOWN",      (char *)"KEY_BRIGHTNESSUP",      (char *)"KEY_MEDIA",      (char *)"KEY_SWITCHVIDEOMODE", 
        (char *)"KEY_KBDILLUMTOGGLE",      (char *)"KEY_KBDILLUMDOWN",      (char *)"KEY_KBDILLUMUP",      (char *)"KEY_SEND", 
        (char *)"KEY_REPLY",      (char *)"KEY_FORWARDMAIL",      (char *)"KEY_SAVE",      (char *)"KEY_DOCUMENTS", 
        (char *)"KEY_BATTERY",      (char *)"KEY_BLUETOOTH",      (char *)"KEY_WLAN",      (char *)"KEY_UWB", 
        (char *)"KEY_UNKNOWN",      (char *)"KEY_VIDEO_NEXT",      (char *)"KEY_VIDEO_PREV",      (char *)"KEY_BRIGHTNESS_CYCLE", 
        (char *)"KEY_BRIGHTNESS_ZERO",      (char *)"KEY_DISPLAY_OFF",      (char *)"KEY_WIMAX",      (char *)"KEY_RFKILL", 
        (char *)"KEY_MICMUTE",      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)"BTN_0",      (char *)"BTN_1",      (char *)"BTN_2",      (char *)"BTN_3", 
        (char *)"BTN_4",      (char *)"BTN_5",      (char *)"BTN_6",      (char *)"BTN_7", 
        (char *)"BTN_8",      (char *)"BTN_9",      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)"BTN_LEFT",      (char *)"BTN_RIGHT",      (char *)"BTN_MIDDLE",      (char *)"BTN_SIDE", 
        (char *)"BTN_EXTRA",      (char *)"BTN_FORWARD",      (char *)"BTN_BACK",      (char *)"BTN_TASK", 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)"BTN_TRIGGER",      (char *)"BTN_THUMB",      (char *)"BTN_THUMB2",      (char *)"BTN_TOP", 
        (char *)"BTN_TOP2",      (char *)"BTN_PINKIE",      (char *)"BTN_BASE",      (char *)"BTN_BASE2", 
        (char *)"BTN_BASE3",      (char *)"BTN_BASE4",      (char *)"BTN_BASE5",      (char *)"BTN_BASE6", 
        (char *)0,      (char *)0,      (char *)0,      (char *)"BTN_DEAD", 
        (char *)"BTN_A",      (char *)"BTN_B",      (char *)"BTN_C",      (char *)"BTN_X", 
        (char *)"BTN_Y",      (char *)"BTN_Z",      (char *)"BTN_TL",      (char *)"BTN_TR", 
        (char *)"BTN_TL2",      (char *)"BTN_TR2",      (char *)"BTN_SELECT",      (char *)"BTN_START", 
        (char *)"BTN_MODE",      (char *)"BTN_THUMBL",      (char *)"BTN_THUMBR",      (char *)0, 
        (char *)"BTN_TOOL_PEN",      (char *)"BTN_TOOL_RUBBER",      (char *)"BTN_TOOL_BRUSH",      (char *)"BTN_TOOL_PENCIL", 
        (char *)"BTN_TOOL_AIRBRUSH",      (char *)"BTN_TOOL_FINGER",      (char *)"BTN_TOOL_MOUSE",      (char *)"BTN_TOOL_LENS", 
        (char *)"BTN_TOOL_QUINTTAP",      (char *)0,      (char *)"BTN_TOUCH",      (char *)"BTN_STYLUS", 
        (char *)"BTN_STYLUS2",      (char *)"BTN_TOOL_DOUBLETAP",      (char *)"BTN_TOOL_TRIPLETAP",      (char *)"BTN_TOOL_QUADTAP", 
        (char *)"BTN_GEAR_DOWN",      (char *)"BTN_GEAR_UP",      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)"KEY_OK",      (char *)"KEY_SELECT",      (char *)"KEY_GOTO",      (char *)"KEY_CLEAR", 
        (char *)"KEY_POWER2",      (char *)"KEY_OPTION",      (char *)"KEY_INFO",      (char *)"KEY_TIME", 
        (char *)"KEY_VENDOR",      (char *)"KEY_ARCHIVE",      (char *)"KEY_PROGRAM",      (char *)"KEY_CHANNEL", 
        (char *)"KEY_FAVORITES",      (char *)"KEY_EPG",      (char *)"KEY_PVR",      (char *)"KEY_MHP", 
        (char *)"KEY_LANGUAGE",      (char *)"KEY_TITLE",      (char *)"KEY_SUBTITLE",      (char *)"KEY_ANGLE", 
        (char *)"KEY_ZOOM",      (char *)"KEY_MODE",      (char *)"KEY_KEYBOARD",      (char *)"KEY_SCREEN", 
        (char *)"KEY_PC",      (char *)"KEY_TV",      (char *)"KEY_TV2",      (char *)"KEY_VCR", 
        (char *)"KEY_VCR2",      (char *)"KEY_SAT",      (char *)"KEY_SAT2",      (char *)"KEY_CD", 
        (char *)"KEY_TAPE",      (char *)"KEY_RADIO",      (char *)"KEY_TUNER",      (char *)"KEY_PLAYER", 
        (char *)"KEY_TEXT",      (char *)"KEY_DVD",      (char *)"KEY_AUX",      (char *)"KEY_MP3", 
        (char *)"KEY_AUDIO",      (char *)"KEY_VIDEO",      (char *)"KEY_DIRECTORY",      (char *)"KEY_LIST", 
        (char *)"KEY_MEMO",      (char *)"KEY_CALENDAR",      (char *)"KEY_RED",      (char *)"KEY_GREEN", 
        (char *)"KEY_YELLOW",      (char *)"KEY_BLUE",      (char *)"KEY_CHANNELUP",      (char *)"KEY_CHANNELDOWN", 
        (char *)"KEY_FIRST",      (char *)"KEY_LAST",      (char *)"KEY_AB",      (char *)"KEY_NEXT", 
        (char *)"KEY_RESTART",      (char *)"KEY_SLOW",      (char *)"KEY_SHUFFLE",      (char *)"KEY_BREAK", 
        (char *)"KEY_PREVIOUS",      (char *)"KEY_DIGITS",      (char *)"KEY_TEEN",      (char *)"KEY_TWEN", 
        (char *)"KEY_VIDEOPHONE",      (char *)"KEY_GAMES",      (char *)"KEY_ZOOMIN",      (char *)"KEY_ZOOMOUT", 
        (char *)"KEY_ZOOMRESET",      (char *)"KEY_WORDPROCESSOR",      (char *)"KEY_EDITOR",      (char *)"KEY_SPREADSHEET", 
        (char *)"KEY_GRAPHICSEDITOR",      (char *)"KEY_PRESENTATION",      (char *)"KEY_DATABASE",      (char *)"KEY_NEWS", 
        (char *)"KEY_VOICEMAIL",      (char *)"KEY_ADDRESSBOOK",      (char *)"KEY_MESSENGER",      (char *)"KEY_DISPLAYTOGGLE", 
        (char *)"KEY_SPELLCHECK",      (char *)"KEY_LOGOFF",      (char *)"KEY_DOLLAR",      (char *)"KEY_EURO", 
        (char *)"KEY_FRAMEBACK",      (char *)"KEY_FRAMEFORWARD",      (char *)"KEY_CONTEXT_MENU",      (char *)"KEY_MEDIA_REPEAT", 
        (char *)"KEY_10CHANNELSUP",      (char *)"KEY_10CHANNELSDOWN",      (char *)"KEY_IMAGES",      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)"KEY_DEL_EOL",      (char *)"KEY_DEL_EOS",      (char *)"KEY_INS_LINE",      (char *)"KEY_DEL_LINE", 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)"KEY_FN",      (char *)"KEY_FN_ESC",      (char *)"KEY_FN_F1",      (char *)"KEY_FN_F2", 
        (char *)"KEY_FN_F3",      (char *)"KEY_FN_F4",      (char *)"KEY_FN_F5",      (char *)"KEY_FN_F6", 
        (char *)"KEY_FN_F7",      (char *)"KEY_FN_F8",      (char *)"KEY_FN_F9",      (char *)"KEY_FN_F10", 
        (char *)"KEY_FN_F11",      (char *)"KEY_FN_F12",      (char *)"KEY_FN_1",      (char *)"KEY_FN_2", 
        (char *)"KEY_FN_D",      (char *)"KEY_FN_E",      (char *)"KEY_FN_F",      (char *)"KEY_FN_S", 
        (char *)"KEY_FN_B",      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)"KEY_BRL_DOT1",      (char *)"KEY_BRL_DOT2",      (char *)"KEY_BRL_DOT3", 
        (char *)"KEY_BRL_DOT4",      (char *)"KEY_BRL_DOT5",      (char *)"KEY_BRL_DOT6",      (char *)"KEY_BRL_DOT7", 
        (char *)"KEY_BRL_DOT8",      (char *)"KEY_BRL_DOT9",      (char *)"KEY_BRL_DOT10",      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)"KEY_NUMERIC_0",      (char *)"KEY_NUMERIC_1",      (char *)"KEY_NUMERIC_2",      (char *)"KEY_NUMERIC_3", 
        (char *)"KEY_NUMERIC_4",      (char *)"KEY_NUMERIC_5",      (char *)"KEY_NUMERIC_6",      (char *)"KEY_NUMERIC_7", 
        (char *)"KEY_NUMERIC_8",      (char *)"KEY_NUMERIC_9",      (char *)"KEY_NUMERIC_STAR",      (char *)"KEY_NUMERIC_POUND", 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)"KEY_CAMERA_FOCUS",      (char *)"KEY_WPS_BUTTON",      (char *)"KEY_TOUCHPAD_TOGGLE",      (char *)"KEY_TOUCHPAD_ON", 
        (char *)"KEY_TOUCHPAD_OFF",      (char *)"KEY_CAMERA_ZOOMIN",      (char *)"KEY_CAMERA_ZOOMOUT",      (char *)"KEY_CAMERA_UP", 
        (char *)"KEY_CAMERA_DOWN",      (char *)"KEY_CAMERA_LEFT",      (char *)"KEY_CAMERA_RIGHT",      (char *)"KEY_ATTENDANT_ON", 
        (char *)"KEY_ATTENDANT_OFF",      (char *)"KEY_ATTENDANT_TOGGLE",      (char *)"KEY_LIGHTS_TOGGLE",      (char *)0, 
        (char *)"BTN_DPAD_UP",      (char *)"BTN_DPAD_DOWN",      (char *)"BTN_DPAD_LEFT",      (char *)"BTN_DPAD_RIGHT", 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)"KEY_ALS_TOGGLE",      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)"BTN_TRIGGER_HAPPY1",      (char *)"BTN_TRIGGER_HAPPY2",      (char *)"BTN_TRIGGER_HAPPY3",      (char *)"BTN_TRIGGER_HAPPY4", 
        (char *)"BTN_TRIGGER_HAPPY5",      (char *)"BTN_TRIGGER_HAPPY6",      (char *)"BTN_TRIGGER_HAPPY7",      (char *)"BTN_TRIGGER_HAPPY8", 
        (char *)"BTN_TRIGGER_HAPPY9",      (char *)"BTN_TRIGGER_HAPPY10",      (char *)"BTN_TRIGGER_HAPPY11",      (char *)"BTN_TRIGGER_HAPPY12", 
        (char *)"BTN_TRIGGER_HAPPY13",      (char *)"BTN_TRIGGER_HAPPY14",      (char *)"BTN_TRIGGER_HAPPY15",      (char *)"BTN_TRIGGER_HAPPY16", 
        (char *)"BTN_TRIGGER_HAPPY17",      (char *)"BTN_TRIGGER_HAPPY18",      (char *)"BTN_TRIGGER_HAPPY19",      (char *)"BTN_TRIGGER_HAPPY20", 
        (char *)"BTN_TRIGGER_HAPPY21",      (char *)"BTN_TRIGGER_HAPPY22",      (char *)"BTN_TRIGGER_HAPPY23",      (char *)"BTN_TRIGGER_HAPPY24", 
        (char *)"BTN_TRIGGER_HAPPY25",      (char *)"BTN_TRIGGER_HAPPY26",      (char *)"BTN_TRIGGER_HAPPY27",      (char *)"BTN_TRIGGER_HAPPY28", 
        (char *)"BTN_TRIGGER_HAPPY29",      (char *)"BTN_TRIGGER_HAPPY30",      (char *)"BTN_TRIGGER_HAPPY31",      (char *)"BTN_TRIGGER_HAPPY32", 
        (char *)"BTN_TRIGGER_HAPPY33",      (char *)"BTN_TRIGGER_HAPPY34",      (char *)"BTN_TRIGGER_HAPPY35",      (char *)"BTN_TRIGGER_HAPPY36", 
        (char *)"BTN_TRIGGER_HAPPY37",      (char *)"BTN_TRIGGER_HAPPY38",      (char *)"BTN_TRIGGER_HAPPY39",      (char *)"BTN_TRIGGER_HAPPY40"};
#line 51 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.c"
static char *SW_NAME[16]  = 
#line 51
  {      (char *)"SW_LID",      (char *)"SW_TABLET_MODE",      (char *)"SW_HEADPHONE_INSERT",      (char *)"SW_RADIO", 
        (char *)"SW_MICROPHONE_INSERT",      (char *)"SW_DOCK",      (char *)"SW_LINEOUT_INSERT",      (char *)"SW_JACK_PHYSICAL_INSERT", 
        (char *)"SW_VIDEOOUT_INSERT",      (char *)"SW_CAMERA_LENS_COVER",      (char *)"SW_KEYPAD_SLIDE",      (char *)"SW_FRONT_PROXIMITY", 
        (char *)"SW_ROTATE_LOCK",      (char *)"SW_LINEIN_INSERT",      (char *)"SW_MUTE_DEVICE"};
#line 55 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.c"
int EV_TYPE_MAX[32]  = 
#line 55
  {      0,      767,      15,      63, 
        7,      15,      0,      0, 
        0,      0,      0,      0, 
        0,      0,      0,      0, 
        0,      15,      7,      0, 
        1};
#line 66 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.c"
char **EV_TYPE_NAME[32]  = 
#line 66
  {      (char **)0,      KEY_NAME,      REL_NAME,      ABS_NAME, 
        MSC_NAME,      SW_NAME,      (char **)0,      (char **)0, 
        (char **)0,      (char **)0,      (char **)0,      (char **)0, 
        (char **)0,      (char **)0,      (char **)0,      (char **)0, 
        (char **)0,      LED_NAME,      SND_NAME,      (char **)0, 
        REP_NAME};
#line 77 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.c"
char *BUS_NAME[29]  = 
#line 77
  {      (char *)0,      (char *)"BUS_PCI",      (char *)"BUS_ISAPNP",      (char *)"BUS_USB", 
        (char *)"BUS_HIL",      (char *)"BUS_BLUETOOTH",      (char *)"BUS_VIRTUAL",      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)0,      (char *)0,      (char *)0,      (char *)0, 
        (char *)"BUS_ISA",      (char *)"BUS_I8042",      (char *)"BUS_XTKBD",      (char *)"BUS_RS232", 
        (char *)"BUS_GAMEPORT",      (char *)"BUS_PARPORT",      (char *)"BUS_AMIGA",      (char *)"BUS_ADB", 
        (char *)"BUS_I2C",      (char *)"BUS_HOST",      (char *)"BUS_GSC",      (char *)"BUS_ATARI", 
        (char *)"BUS_SPI"};
#line 83 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.c"
int device_open(int nr , int verbose ) 
{ 
  char filename[32] ;
  int fd ;
  int *tmp ;
  char *tmp___0 ;
  void *__cil_tmp7 ;
  char *__cil_tmp8 ;
  char *__cil_tmp9 ;
  char *__cil_tmp10 ;

  {
  {
#line 88
  snprintf((char */* __restrict  */)(filename), sizeof(filename), (char const   */* __restrict  */)"/dev/input/event%d",
           nr);
#line 90
  fd = open((char const   *)(filename), 0);
  }
#line 91
  if (-1 == fd) {
    {
#line 92
    tmp = __errno_location();
#line 92
    tmp___0 = strerror(*tmp);
#line 92
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"open %s: %s\n",
            filename, tmp___0);
    }
#line 94
    return (-1);
  }
#line 96
  if (verbose) {
    {
#line 97
    printf((char const   */* __restrict  */)"%s\n", filename);
    }
  }
#line 99
  return (fd);
}
}
#line 102 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.c"
void device_info(int fd ) 
{ 
  struct input_id id ;
  uint32_t bits[32] ;
  char buf[32] ;
  int rc ;
  int bit ;
  int tmp ;
  void *__cil_tmp8 ;
  void *__cil_tmp9 ;
  char *__cil_tmp10 ;
  char *__cil_tmp11 ;
  char *__cil_tmp12 ;
  char *__cil_tmp13 ;
  char *__cil_tmp14 ;
  char *__cil_tmp15 ;
  char *__cil_tmp16 ;
  char *__cil_tmp17 ;

  {
  {
#line 109
  rc = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(69 << 8)) | 2U) | (sizeof(struct input_id ) << 16),
             & id);
  }
#line 110
  if (rc >= 0) {
    {
#line 111
    printf((char const   */* __restrict  */)"   bustype : %s\n   vendor  : 0x%x\n   product : 0x%x\n   version : %d\n",
           BUS_NAME[id.bustype], (int )id.vendor, (int )id.product, (int )id.version);
    }
  }
  {
#line 118
  rc = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(69 << 8)) | 6U) | (sizeof(buf) << 16),
             buf);
  }
#line 119
  if (rc >= 0) {
    {
#line 120
    printf((char const   */* __restrict  */)"   name    : \"%.*s\"\n", rc, buf);
    }
  }
  {
#line 121
  rc = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(69 << 8)) | 7U) | (sizeof(buf) << 16),
             buf);
  }
#line 122
  if (rc >= 0) {
    {
#line 123
    printf((char const   */* __restrict  */)"   phys    : \"%.*s\"\n", rc, buf);
    }
  }
  {
#line 124
  rc = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(69 << 8)) | 8U) | (sizeof(buf) << 16),
             buf);
  }
#line 125
  if (rc >= 0) {
    {
#line 126
    printf((char const   */* __restrict  */)"   uniq    : \"%.*s\"\n", rc, buf);
    }
  }
  {
#line 127
  rc = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(69 << 8)) | 32U) | (sizeof(bits) << 16),
             bits);
  }
#line 128
  if (rc >= 0) {
    {
#line 129
    printf((char const   */* __restrict  */)"   bits ev :");
#line 130
    bit = 0;
    }
    {
#line 130
    while (1) {
      while_continue: /* CIL Label */ ;

#line 130
      if (bit < rc * 8) {
#line 130
        if (! (bit < 31)) {
#line 130
          goto while_break;
        }
      } else {
#line 130
        goto while_break;
      }
      {
#line 131
      tmp = test_bit(bit, bits);
      }
#line 131
      if (tmp) {
        {
#line 132
        airac_observe(EV_NAME, bit);
#line 132
        printf((char const   */* __restrict  */)" %s", EV_NAME[bit]);
        }
      }
#line 130
      bit ++;
    }
    while_break___0: /* CIL Label */ ;
    }
    while_break: 
    {
#line 134
    printf((char const   */* __restrict  */)"\n");
    }
  }
  {
#line 136
  printf((char const   */* __restrict  */)"\n");
  }
#line 137
  return;
}
}
#line 141 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/input.c"
void print_event(struct input_event *event ) 
{ 
  char ts[32] ;
  time_t t ;
  struct tm *tmp ;
  char const   *tmp___0 ;
  char const   *tmp___1 ;
  char const   *tmp___2 ;
  void *__cil_tmp8 ;
  char *__cil_tmp9 ;
  char *__cil_tmp10 ;
  char *__cil_tmp11 ;
  char *__cil_tmp12 ;
  char *__cil_tmp13 ;
  char *__cil_tmp14 ;
  char *__cil_tmp15 ;
  char *__cil_tmp16 ;
  char *__cil_tmp17 ;
  char *__cil_tmp18 ;
  char *__cil_tmp19 ;
  char *__cil_tmp20 ;

  {
  {
#line 146
  t = event->time.tv_sec;
#line 147
  tmp = localtime((time_t const   *)(& t));
#line 147
  strftime((char */* __restrict  */)(ts), sizeof(ts), (char const   */* __restrict  */)"%H:%M:%S",
           (struct tm  const  */* __restrict  */)((struct tm  const  *)tmp));
#line 148
  printf((char const   */* __restrict  */)"%s.%06ld: %s", ts, event->time.tv_usec,
         EV_NAME[event->type]);
  }
#line 151
  if ((int )event->type == 1) {
#line 151
    goto case_1;
  }
#line 162
  if ((int )event->type == 5) {
#line 162
    goto case_5;
  }
#line 162
  if ((int )event->type == 20) {
#line 162
    goto case_5;
  }
#line 162
  if ((int )event->type == 18) {
#line 162
    goto case_5;
  }
#line 162
  if ((int )event->type == 17) {
#line 162
    goto case_5;
  }
#line 162
  if ((int )event->type == 4) {
#line 162
    goto case_5;
  }
#line 162
  if ((int )event->type == 3) {
#line 162
    goto case_5;
  }
#line 162
  if ((int )event->type == 2) {
#line 162
    goto case_5;
  }
#line 166
  goto switch_default;
  case_1: 
#line 152
  if (event->value) {
#line 152
    tmp___0 = "pressed";
  } else {
#line 152
    tmp___0 = "released";
  }
#line 152
  if ((int )event->code < EV_TYPE_MAX[1]) {
#line 152
    if (*(EV_TYPE_NAME[1] + (int )event->code)) {
#line 152
      tmp___1 = (char const   *)*(EV_TYPE_NAME[1] + (int )event->code);
    } else {
#line 152
      tmp___1 = "???";
    }
  } else {
#line 152
    tmp___1 = "???";
  }
  {
#line 152
  printf((char const   */* __restrict  */)" %s (0x%x) %s", tmp___1, (int )event->code,
         tmp___0);
  }
#line 155
  goto switch_break;
  case_5: 
#line 163
  if ((int )event->code < EV_TYPE_MAX[event->type]) {
#line 163
    if (*(EV_TYPE_NAME[event->type] + (int )event->code)) {
#line 163
      tmp___2 = (char const   *)*(EV_TYPE_NAME[event->type] + (int )event->code);
    } else {
#line 163
      tmp___2 = "???";
    }
  } else {
#line 163
    tmp___2 = "???";
  }
  {
#line 163
  printf((char const   */* __restrict  */)" %s %d", tmp___2, event->value);
  }
#line 165
  goto switch_break;
  switch_default: 
  {
#line 167
  printf((char const   */* __restrict  */)" code=%u value=%d", (unsigned int )event->code,
         event->value);
  }
  switch_break: 
  {
#line 170
  printf((char const   */* __restrict  */)"\n");
  }
#line 171
  return;
}
}
#line 543 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
#line 209 "/usr/include/x86_64-linux-gnu/sys/stat.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,2), __leaf__)) stat)(char const   * __restrict  __file ,
                                                                                             struct stat * __restrict  __buf ) ;
#line 353 "/usr/include/unistd.h"
extern int close(int __fd ) ;
#line 11 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/lsinput.c"
static void list_devices(void) 
{ 
  int i ;
  int fd ;
  char filename[32] ;
  struct stat statbuf ;
  int tmp ;
  void *__cil_tmp6 ;
  void *__cil_tmp7 ;
  char *__cil_tmp8 ;

  {
#line 17
  i = 0;
  {
#line 17
  while (1) {
    while_continue: /* CIL Label */ ;

#line 17
    if (! (i < 32)) {
#line 17
      goto while_break;
    }
    {
#line 18
    snprintf((char */* __restrict  */)(filename), sizeof(filename), (char const   */* __restrict  */)"/dev/input/event%d",
             i);
#line 19
    tmp = stat((char const   */* __restrict  */)((char const   *)(filename)), (struct stat */* __restrict  */)(& statbuf));
    }
#line 19
    if (tmp == 0) {
      {
#line 21
      fd = device_open(i, 1);
      }
#line 22
      if (-1 == fd) {
#line 23
        return;
      }
      {
#line 24
      device_info(fd);
#line 25
      close(fd);
      }
    }
#line 17
    i ++;
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: ;
#line 28
  return;
}
}
#line 31 "/home/june/repo/benchmarks/collector/temp/input-utils-1.0/lsinput.c"
int main(int argc , char **argv ) 
{ 


  {
  {
#line 33
  list_devices();
#line 34
  exit(0);
  }
}
}
