/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 212 "/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h"
typedef unsigned long size_t;
#line 131 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
#line 132 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
#line 139 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __time_t;
#line 141 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __suseconds_t;
#line 172 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __ssize_t;
#line 44 "/usr/include/stdio.h"
struct _IO_FILE;
#line 44
struct _IO_FILE;
#line 48 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 154 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 160 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 245 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 102 "/usr/include/stdio.h"
typedef __ssize_t ssize_t;
#line 30 "/usr/include/x86_64-linux-gnu/bits/time.h"
struct timeval {
   __time_t tv_sec ;
   __suseconds_t tv_usec ;
};
#line 22 "/usr/include/asm-generic/int-ll64.h"
typedef short __s16;
#line 23 "/usr/include/asm-generic/int-ll64.h"
typedef unsigned short __u16;
#line 25 "/usr/include/asm-generic/int-ll64.h"
typedef int __s32;
#line 26 "/usr/include/asm-generic/int-ll64.h"
typedef unsigned int __u32;
#line 22 "/usr/include/linux/input.h"
struct input_event {
   struct timeval time ;
   __u16 type ;
   __u16 code ;
   __s32 value ;
};
#line 974 "/usr/include/linux/input.h"
struct ff_replay {
   __u16 length ;
   __u16 delay ;
};
#line 984 "/usr/include/linux/input.h"
struct ff_trigger {
   __u16 button ;
   __u16 interval ;
};
#line 1001 "/usr/include/linux/input.h"
struct ff_envelope {
   __u16 attack_length ;
   __u16 attack_level ;
   __u16 fade_length ;
   __u16 fade_level ;
};
#line 1013 "/usr/include/linux/input.h"
struct ff_constant_effect {
   __s16 level ;
   struct ff_envelope envelope ;
};
#line 1024 "/usr/include/linux/input.h"
struct ff_ramp_effect {
   __s16 start_level ;
   __s16 end_level ;
   struct ff_envelope envelope ;
};
#line 1040 "/usr/include/linux/input.h"
struct ff_condition_effect {
   __u16 right_saturation ;
   __u16 left_saturation ;
   __s16 right_coeff ;
   __s16 left_coeff ;
   __u16 deadband ;
   __s16 center ;
};
#line 1069 "/usr/include/linux/input.h"
struct ff_periodic_effect {
   __u16 waveform ;
   __u16 period ;
   __s16 magnitude ;
   __s16 offset ;
   __u16 phase ;
   struct ff_envelope envelope ;
   __u32 custom_len ;
   __s16 *custom_data ;
};
#line 1090 "/usr/include/linux/input.h"
struct ff_rumble_effect {
   __u16 strong_magnitude ;
   __u16 weak_magnitude ;
};
#line 1118 "/usr/include/linux/input.h"
union __anonunion_u_30 {
   struct ff_constant_effect constant ;
   struct ff_ramp_effect ramp ;
   struct ff_periodic_effect periodic ;
   struct ff_condition_effect condition[2] ;
   struct ff_rumble_effect rumble ;
};
#line 1118 "/usr/include/linux/input.h"
struct ff_effect {
   __u16 type ;
   __s16 id ;
   __u16 direction ;
   struct ff_trigger trigger ;
   struct ff_replay replay ;
   union __anonunion_u_30 u ;
};
#line 54 "/usr/include/x86_64-linux-gnu/sys/select.h"
typedef long __fd_mask;
#line 64 "/usr/include/x86_64-linux-gnu/sys/select.h"
struct __anonstruct_fd_set_15 {
   __fd_mask __fds_bits[1024 / (8 * (int )sizeof(__fd_mask ))] ;
};
#line 64 "/usr/include/x86_64-linux-gnu/sys/select.h"
typedef struct __anonstruct_fd_set_15 fd_set;
#line 48 "/usr/include/stdint.h"
typedef unsigned char uint8_t;
#line 49 "/usr/include/stdint.h"
typedef unsigned short uint16_t;
#line 20 "/usr/include/asm-generic/int-ll64.h"
typedef unsigned char __u8;
#line 55 "/usr/include/x86_64-linux-gnu/sys/time.h"
struct timezone {
   int tz_minuteswest ;
   int tz_dsttime ;
};
#line 61 "/usr/include/x86_64-linux-gnu/sys/time.h"
typedef struct timezone * __restrict  __timezone_ptr_t;
#line 47 "/usr/include/linux/joystick.h"
struct js_event {
   __u32 time ;
   __s16 value ;
   __u8 type ;
   __u8 number ;
};
#line 79 "/usr/include/linux/joystick.h"
struct js_corr {
   __s32 coef[8] ;
   __s16 prec ;
   __u16 type ;
};
#line 53 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
struct correction_data {
   int cmin[3] ;
   int cmax[3] ;
};
#line 67 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
struct js_info {
   int buttons ;
   int axis[64] ;
};
/* compiler builtin: 
   void *__builtin_alloca(unsigned long  ) ;  */
#line 169 "/usr/include/stdio.h"
extern struct _IO_FILE *stdout ;
#line 242
extern int fflush(FILE *__stream ) ;
#line 362
extern int printf(char const   * __restrict  __format  , ...) ;
#line 431
extern int scanf(char const   * __restrict  __format  , ...)  __asm__("__isoc99_scanf")  ;
#line 846
extern void perror(char const   *__s ) ;
#line 146 "/usr/include/fcntl.h"
extern int ( __attribute__((__nonnull__(1))) open)(char const   *__file , int __oflag 
                                                   , ...) ;
#line 366 "/usr/include/unistd.h"
extern ssize_t write(int __fd , void const   *__buf , size_t __n ) ;
#line 543 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
#line 66 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) void *( __attribute__((__nonnull__(1), __leaf__)) memset)(void *__s ,
                                                                                               int __c ,
                                                                                               size_t __n ) ;
#line 147
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1,2), __leaf__)) strncmp)(char const   *__s1 ,
                                                                                                char const   *__s2 ,
                                                                                                size_t __n )  __attribute__((__pure__)) ;
#line 41 "/usr/include/x86_64-linux-gnu/sys/ioctl.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) ioctl)(int __fd ,
                                                                            unsigned long __request 
                                                                            , ...) ;
#line 43 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/fftest.c"
char *effect_names[6]  = {      (char *)"Sine vibration",      (char *)"Constant Force",      (char *)"Spring Condition",      (char *)"Damping Condition", 
        (char *)"Strong Rumble",      (char *)"Weak Rumble"};
#line 52 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/fftest.c"
int main(int argc , char **argv ) 
{ 
  struct ff_effect effects[6] ;
  struct input_event play ;
  struct input_event stop ;
  struct input_event gain ;
  int fd___0 ;
  char const   *device_file_name ;
  unsigned char relFeatures[1UL + 1UL / sizeof(unsigned char )] ;
  unsigned char absFeatures[1UL + 7UL / sizeof(unsigned char )] ;
  unsigned char ffFeatures[1UL + 15UL / sizeof(unsigned char )] ;
  int n_effects ;
  int i ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  ssize_t tmp___4 ;
  int tmp___5 ;
  int tmp___6 ;
  int tmp___7 ;
  int tmp___8 ;
  int tmp___9 ;
  int tmp___10 ;
  ssize_t tmp___11 ;
  int i___0 ;
  int tmp___12 ;
  ssize_t tmp___13 ;
  void *__cil_tmp30 ;
  int __cil_tmp31 ;
  void *__cil_tmp32 ;
  int __cil_tmp33 ;
  void *__cil_tmp34 ;
  void *__cil_tmp35 ;
  void *__cil_tmp36 ;
  char *__cil_tmp37 ;
  char *__cil_tmp38 ;
  char *__cil_tmp39 ;
  char *__cil_tmp40 ;
  char *__cil_tmp41 ;
  char *__cil_tmp42 ;
  char *__cil_tmp43 ;
  char *__cil_tmp44 ;
  char *__cil_tmp45 ;
  char *__cil_tmp46 ;
  char *__cil_tmp47 ;
  char *__cil_tmp48 ;
  char *__cil_tmp49 ;
  char *__cil_tmp50 ;
  char *__cil_tmp51 ;
  char *__cil_tmp52 ;
  char *__cil_tmp53 ;
  char *__cil_tmp54 ;
  char *__cil_tmp55 ;
  char *__cil_tmp56 ;
  char *__cil_tmp57 ;
  char *__cil_tmp58 ;
  char *__cil_tmp59 ;
  char *__cil_tmp60 ;
  char *__cil_tmp61 ;
  char *__cil_tmp62 ;
  char *__cil_tmp63 ;
  char *__cil_tmp64 ;
  char *__cil_tmp65 ;
  char *__cil_tmp66 ;
  char *__cil_tmp67 ;
  char *__cil_tmp68 ;
  char *__cil_tmp69 ;
  char *__cil_tmp70 ;
  char *__cil_tmp71 ;
  char *__cil_tmp72 ;
  char *__cil_tmp73 ;
  char *__cil_tmp74 ;
  char *__cil_tmp75 ;
  char *__cil_tmp76 ;
  char *__cil_tmp77 ;
  char *__cil_tmp78 ;
  char *__cil_tmp79 ;
  char *__cil_tmp80 ;
  char *__cil_tmp81 ;
  char *__cil_tmp82 ;
  char *__cil_tmp83 ;
  char *__cil_tmp84 ;
  char *__cil_tmp85 ;
  char *__cil_tmp86 ;
  char *__cil_tmp87 ;
  char *__cil_tmp88 ;
  char *__cil_tmp89 ;
  char *__cil_tmp90 ;
  char *__cil_tmp91 ;
  char *__cil_tmp92 ;
  char *__cil_tmp93 ;
  char *__cil_tmp94 ;
  char *__cil_tmp95 ;
  char *__cil_tmp96 ;
  char *__cil_tmp97 ;
  char *__cil_tmp98 ;
  char *__cil_tmp99 ;
  char *__cil_tmp100 ;
  char *__cil_tmp101 ;
  char *__cil_tmp102 ;
  char *__cil_tmp103 ;
  char *__cil_tmp104 ;
  char *__cil_tmp105 ;
  char *__cil_tmp106 ;
  char *__cil_tmp107 ;
  char *__cil_tmp108 ;
  char *__cil_tmp109 ;
  char *__cil_tmp110 ;
  char *__cil_tmp111 ;
  char *__cil_tmp112 ;
  char *__cil_tmp113 ;
  char *__cil_tmp114 ;
  char *__cil_tmp115 ;
  char *__cil_tmp116 ;
  char *__cil_tmp117 ;
  char *__cil_tmp118 ;
  char *__cil_tmp119 ;
  char *__cil_tmp120 ;
  char *__cil_tmp121 ;
  char *__cil_tmp122 ;
  char *__cil_tmp123 ;
  char *__cil_tmp124 ;
  char *__cil_tmp125 ;
  char *__cil_tmp126 ;
  char *__cil_tmp127 ;
  char *__cil_tmp128 ;
  char *__cil_tmp129 ;
  char *__cil_tmp130 ;
  char *__cil_tmp131 ;
  char *__cil_tmp132 ;
  char *__cil_tmp133 ;
  char *__cil_tmp134 ;
  char *__cil_tmp135 ;
  char *__cil_tmp136 ;
  char *__cil_tmp137 ;
  char *__cil_tmp138 ;
  char *__cil_tmp139 ;
  char *__cil_tmp140 ;
  char *__cil_tmp141 ;
  char *__cil_tmp142 ;
  char *__cil_tmp143 ;
  char *__cil_tmp144 ;
  char *__cil_tmp145 ;
  char *__cil_tmp146 ;

  {
  {
#line 57
  device_file_name = "/dev/input/event0";
#line 64
  printf((char const   */* __restrict  */)"Force feedback test program.\n");
#line 65
  printf((char const   */* __restrict  */)"HOLD FIRMLY YOUR WHEEL OR JOYSTICK TO PREVENT DAMAGES\n\n");
#line 67
  i = 1;
  }
  {
#line 67
  while (1) {
    while_continue: /* CIL Label */ ;

#line 67
    if (! (i < argc)) {
#line 67
      goto while_break;
    }
    {
#line 68
    tmp = strncmp((char const   *)*(argv + i), "--help", (size_t )64);
    }
#line 68
    if (tmp == 0) {
      {
#line 69
      printf((char const   */* __restrict  */)"Usage: %s /dev/input/eventXX\n", *(argv + 0));
#line 70
      printf((char const   */* __restrict  */)"Tests the force feedback driver\n");
#line 71
      exit(1);
      }
    } else {
#line 74
      device_file_name = (char const   *)*(argv + i);
    }
#line 67
    i ++;
  }
  while_break___5: /* CIL Label */ ;
  }
  while_break: 
  {
#line 79
  fd___0 = open(device_file_name, 2);
  }
#line 80
  if (fd___0 == -1) {
    {
#line 81
    perror("Open device file");
#line 82
    exit(1);
    }
  }
  {
#line 84
  printf((char const   */* __restrict  */)"Device %s opened\n", device_file_name);
#line 87
  printf((char const   */* __restrict  */)"Features:\n");
#line 90
  memset((void *)(absFeatures), 0, sizeof(absFeatures) * sizeof(unsigned char ));
#line 91
  tmp___0 = ioctl(fd___0, (unsigned long )(((2U << 30) | (unsigned int )(69 << 8)) | 35U) | (sizeof(absFeatures) * sizeof(unsigned char ) << 16),
                  absFeatures);
  }
#line 91
  if (tmp___0 == -1) {
    {
#line 92
    perror("Ioctl absolute axes features query");
#line 93
    exit(1);
    }
  }
  {
#line 96
  printf((char const   */* __restrict  */)"  * Absolute axes: ");
  }
#line 98
  if (((int )absFeatures[0UL / (sizeof(unsigned char ) * 8UL)] >> 0UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 98
    printf((char const   */* __restrict  */)"X, ");
    }
  }
#line 99
  if (((int )absFeatures[1UL / (sizeof(unsigned char ) * 8UL)] >> 1UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 99
    printf((char const   */* __restrict  */)"Y, ");
    }
  }
#line 100
  if (((int )absFeatures[2UL / (sizeof(unsigned char ) * 8UL)] >> 2UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 100
    printf((char const   */* __restrict  */)"Z, ");
    }
  }
#line 101
  if (((int )absFeatures[3UL / (sizeof(unsigned char ) * 8UL)] >> 3UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 101
    printf((char const   */* __restrict  */)"RX, ");
    }
  }
#line 102
  if (((int )absFeatures[4UL / (sizeof(unsigned char ) * 8UL)] >> 4UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 102
    printf((char const   */* __restrict  */)"RY, ");
    }
  }
#line 103
  if (((int )absFeatures[5UL / (sizeof(unsigned char ) * 8UL)] >> 5UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 103
    printf((char const   */* __restrict  */)"RZ, ");
    }
  }
#line 104
  if (((int )absFeatures[6UL / (sizeof(unsigned char ) * 8UL)] >> 6UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 104
    printf((char const   */* __restrict  */)"Throttle, ");
    }
  }
#line 105
  if (((int )absFeatures[7UL / (sizeof(unsigned char ) * 8UL)] >> 7UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 105
    printf((char const   */* __restrict  */)"Rudder, ");
    }
  }
#line 106
  if (((int )absFeatures[8UL / (sizeof(unsigned char ) * 8UL)] >> 8UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 106
    printf((char const   */* __restrict  */)"Wheel, ");
    }
  }
#line 107
  if (((int )absFeatures[9UL / (sizeof(unsigned char ) * 8UL)] >> 9UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 107
    printf((char const   */* __restrict  */)"Gas, ");
    }
  }
#line 108
  if (((int )absFeatures[10UL / (sizeof(unsigned char ) * 8UL)] >> 10UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 108
    printf((char const   */* __restrict  */)"Brake, ");
    }
  }
#line 109
  if (((int )absFeatures[16UL / (sizeof(unsigned char ) * 8UL)] >> 16UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 109
    printf((char const   */* __restrict  */)"Hat 0 X, ");
    }
  }
#line 110
  if (((int )absFeatures[17UL / (sizeof(unsigned char ) * 8UL)] >> 17UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 110
    printf((char const   */* __restrict  */)"Hat 0 Y, ");
    }
  }
#line 111
  if (((int )absFeatures[18UL / (sizeof(unsigned char ) * 8UL)] >> 18UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 111
    printf((char const   */* __restrict  */)"Hat 1 X, ");
    }
  }
#line 112
  if (((int )absFeatures[19UL / (sizeof(unsigned char ) * 8UL)] >> 19UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 112
    printf((char const   */* __restrict  */)"Hat 1 Y, ");
    }
  }
#line 113
  if (((int )absFeatures[20UL / (sizeof(unsigned char ) * 8UL)] >> 20UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 113
    printf((char const   */* __restrict  */)"Hat 2 X, ");
    }
  }
#line 114
  if (((int )absFeatures[21UL / (sizeof(unsigned char ) * 8UL)] >> 21UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 114
    printf((char const   */* __restrict  */)"Hat 2 Y, ");
    }
  }
#line 115
  if (((int )absFeatures[22UL / (sizeof(unsigned char ) * 8UL)] >> 22UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 115
    printf((char const   */* __restrict  */)"Hat 3 X, ");
    }
  }
#line 116
  if (((int )absFeatures[23UL / (sizeof(unsigned char ) * 8UL)] >> 23UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 116
    printf((char const   */* __restrict  */)"Hat 3 Y, ");
    }
  }
#line 117
  if (((int )absFeatures[24UL / (sizeof(unsigned char ) * 8UL)] >> 24UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 117
    printf((char const   */* __restrict  */)"Pressure, ");
    }
  }
#line 118
  if (((int )absFeatures[25UL / (sizeof(unsigned char ) * 8UL)] >> 25UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 118
    printf((char const   */* __restrict  */)"Distance, ");
    }
  }
#line 119
  if (((int )absFeatures[26UL / (sizeof(unsigned char ) * 8UL)] >> 26UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 119
    printf((char const   */* __restrict  */)"Tilt X, ");
    }
  }
#line 120
  if (((int )absFeatures[27UL / (sizeof(unsigned char ) * 8UL)] >> 27UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 120
    printf((char const   */* __restrict  */)"Tilt Y, ");
    }
  }
#line 121
  if (((int )absFeatures[28UL / (sizeof(unsigned char ) * 8UL)] >> 28UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 121
    printf((char const   */* __restrict  */)"Tool width, ");
    }
  }
#line 122
  if (((int )absFeatures[32UL / (sizeof(unsigned char ) * 8UL)] >> 32UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 122
    printf((char const   */* __restrict  */)"Volume, ");
    }
  }
#line 123
  if (((int )absFeatures[40UL / (sizeof(unsigned char ) * 8UL)] >> 40UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 123
    printf((char const   */* __restrict  */)"Misc ,");
    }
  }
  {
#line 125
  printf((char const   */* __restrict  */)"\n    [");
#line 126
  i = 0;
  }
  {
#line 126
  while (1) {
    while_continue___0: /* CIL Label */ ;

#line 126
    if (! ((unsigned long )i < sizeof(absFeatures) / sizeof(unsigned char ))) {
#line 126
      goto while_break___0;
    }
    {
#line 127
    airac_observe(absFeatures, i);
#line 127
    printf((char const   */* __restrict  */)"%02X ", (int )absFeatures[i]);
#line 126
    i ++;
    }
  }
  while_break___6: /* CIL Label */ ;
  }
  while_break___0: 
  {
#line 128
  printf((char const   */* __restrict  */)"]\n");
#line 131
  memset((void *)(relFeatures), 0, sizeof(relFeatures) * sizeof(unsigned char ));
#line 132
  tmp___1 = ioctl(fd___0, (unsigned long )(((2U << 30) | (unsigned int )(69 << 8)) | 34U) | (sizeof(relFeatures) * sizeof(unsigned char ) << 16),
                  relFeatures);
  }
#line 132
  if (tmp___1 == -1) {
    {
#line 133
    perror("Ioctl relative axes features query");
#line 134
    exit(1);
    }
  }
  {
#line 137
  printf((char const   */* __restrict  */)"  * Relative axes: ");
  }
#line 139
  if (((int )relFeatures[0UL / (sizeof(unsigned char ) * 8UL)] >> 0UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 139
    printf((char const   */* __restrict  */)"X, ");
    }
  }
#line 140
  if (((int )relFeatures[1UL / (sizeof(unsigned char ) * 8UL)] >> 1UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 140
    printf((char const   */* __restrict  */)"Y, ");
    }
  }
#line 141
  if (((int )relFeatures[2UL / (sizeof(unsigned char ) * 8UL)] >> 2UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 141
    printf((char const   */* __restrict  */)"Z, ");
    }
  }
#line 142
  if (((int )relFeatures[3UL / (sizeof(unsigned char ) * 8UL)] >> 3UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 142
    printf((char const   */* __restrict  */)"RX, ");
    }
  }
#line 143
  if (((int )relFeatures[4UL / (sizeof(unsigned char ) * 8UL)] >> 4UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 143
    printf((char const   */* __restrict  */)"RY, ");
    }
  }
#line 144
  if (((int )relFeatures[5UL / (sizeof(unsigned char ) * 8UL)] >> 5UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 144
    printf((char const   */* __restrict  */)"RZ, ");
    }
  }
#line 145
  if (((int )relFeatures[6UL / (sizeof(unsigned char ) * 8UL)] >> 6UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 145
    printf((char const   */* __restrict  */)"HWheel, ");
    }
  }
#line 146
  if (((int )relFeatures[7UL / (sizeof(unsigned char ) * 8UL)] >> 7UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 146
    printf((char const   */* __restrict  */)"Dial, ");
    }
  }
#line 147
  if (((int )relFeatures[8UL / (sizeof(unsigned char ) * 8UL)] >> 8UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 147
    printf((char const   */* __restrict  */)"Wheel, ");
    }
  }
#line 148
  if (((int )relFeatures[9UL / (sizeof(unsigned char ) * 8UL)] >> 9UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 148
    printf((char const   */* __restrict  */)"Misc, ");
    }
  }
  {
#line 150
  printf((char const   */* __restrict  */)"\n    [");
#line 151
  i = 0;
  }
  {
#line 151
  while (1) {
    while_continue___1: /* CIL Label */ ;

#line 151
    if (! ((unsigned long )i < sizeof(relFeatures) / sizeof(unsigned char ))) {
#line 151
      goto while_break___1;
    }
    {
#line 152
    printf((char const   */* __restrict  */)"%02X ", (int )relFeatures[i]);
#line 151
    i ++;
    }
  }
  while_break___7: /* CIL Label */ ;
  }
  while_break___1: 
  {
#line 153
  printf((char const   */* __restrict  */)"]\n");
#line 156
  memset((void *)(ffFeatures), 0, sizeof(ffFeatures) * sizeof(unsigned char ));
#line 157
  tmp___2 = ioctl(fd___0, (unsigned long )(((2U << 30) | (unsigned int )(69 << 8)) | 53U) | (sizeof(ffFeatures) * sizeof(unsigned char ) << 16),
                  ffFeatures);
  }
#line 157
  if (tmp___2 == -1) {
    {
#line 158
    perror("Ioctl force feedback features query");
#line 159
    exit(1);
    }
  }
  {
#line 162
  printf((char const   */* __restrict  */)"  * Force feedback effects types: ");
  }
#line 164
  if (((int )ffFeatures[82UL / (sizeof(unsigned char ) * 8UL)] >> 82UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 164
    printf((char const   */* __restrict  */)"Constant, ");
    }
  }
#line 165
  if (((int )ffFeatures[81UL / (sizeof(unsigned char ) * 8UL)] >> 81UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 165
    printf((char const   */* __restrict  */)"Periodic, ");
    }
  }
#line 166
  if (((int )ffFeatures[87UL / (sizeof(unsigned char ) * 8UL)] >> 87UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 166
    printf((char const   */* __restrict  */)"Ramp, ");
    }
  }
#line 167
  if (((int )ffFeatures[83UL / (sizeof(unsigned char ) * 8UL)] >> 83UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 167
    printf((char const   */* __restrict  */)"Spring, ");
    }
  }
#line 168
  if (((int )ffFeatures[84UL / (sizeof(unsigned char ) * 8UL)] >> 84UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 168
    printf((char const   */* __restrict  */)"Friction, ");
    }
  }
#line 169
  if (((int )ffFeatures[85UL / (sizeof(unsigned char ) * 8UL)] >> 85UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 169
    printf((char const   */* __restrict  */)"Damper, ");
    }
  }
#line 170
  if (((int )ffFeatures[80UL / (sizeof(unsigned char ) * 8UL)] >> 80UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 170
    printf((char const   */* __restrict  */)"Rumble, ");
    }
  }
#line 171
  if (((int )ffFeatures[86UL / (sizeof(unsigned char ) * 8UL)] >> 86UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 171
    printf((char const   */* __restrict  */)"Inertia, ");
    }
  }
#line 172
  if (((int )ffFeatures[96UL / (sizeof(unsigned char ) * 8UL)] >> 96UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 172
    printf((char const   */* __restrict  */)"Gain, ");
    }
  }
#line 173
  if (((int )ffFeatures[97UL / (sizeof(unsigned char ) * 8UL)] >> 97UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 173
    printf((char const   */* __restrict  */)"Autocenter, ");
    }
  }
  {
#line 175
  printf((char const   */* __restrict  */)"\n    Force feedback periodic effects: ");
  }
#line 177
  if (((int )ffFeatures[88UL / (sizeof(unsigned char ) * 8UL)] >> 88UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 177
    printf((char const   */* __restrict  */)"Square, ");
    }
  }
#line 178
  if (((int )ffFeatures[89UL / (sizeof(unsigned char ) * 8UL)] >> 89UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 178
    printf((char const   */* __restrict  */)"Triangle, ");
    }
  }
#line 179
  if (((int )ffFeatures[90UL / (sizeof(unsigned char ) * 8UL)] >> 90UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 179
    printf((char const   */* __restrict  */)"Sine, ");
    }
  }
#line 180
  if (((int )ffFeatures[91UL / (sizeof(unsigned char ) * 8UL)] >> 91UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 180
    printf((char const   */* __restrict  */)"Saw up, ");
    }
  }
#line 181
  if (((int )ffFeatures[92UL / (sizeof(unsigned char ) * 8UL)] >> 92UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 181
    printf((char const   */* __restrict  */)"Saw down, ");
    }
  }
#line 182
  if (((int )ffFeatures[93UL / (sizeof(unsigned char ) * 8UL)] >> 93UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 182
    printf((char const   */* __restrict  */)"Custom, ");
    }
  }
  {
#line 184
  printf((char const   */* __restrict  */)"\n    [");
#line 185
  i = 0;
  }
  {
#line 185
  while (1) {
    while_continue___2: /* CIL Label */ ;

#line 185
    if (! ((unsigned long )i < sizeof(ffFeatures) / sizeof(unsigned char ))) {
#line 185
      goto while_break___2;
    }
    {
#line 186
    printf((char const   */* __restrict  */)"%02X ", (int )ffFeatures[i]);
#line 185
    i ++;
    }
  }
  while_break___8: /* CIL Label */ ;
  }
  while_break___2: 
  {
#line 187
  printf((char const   */* __restrict  */)"]\n");
#line 189
  printf((char const   */* __restrict  */)"  * Number of simultaneous effects: ");
#line 191
  tmp___3 = ioctl(fd___0, (unsigned long )(((2U << 30) | (unsigned int )(69 << 8)) | 132U) | (sizeof(int ) << 16),
                  & n_effects);
  }
#line 191
  if (tmp___3 == -1) {
    {
#line 192
    perror("Ioctl number of effects");
    }
  }
  {
#line 195
  printf((char const   */* __restrict  */)"%d\n\n", n_effects);
  }
#line 198
  if (((int )ffFeatures[96UL / (sizeof(unsigned char ) * 8UL)] >> 96UL % (sizeof(unsigned char ) * 8UL)) & 1) {
    {
#line 199
    memset((void *)(& gain), 0, sizeof(gain));
#line 200
    gain.type = (__u16 )21;
#line 201
    gain.code = (__u16 )96;
#line 202
    gain.value = 49152;
#line 204
    printf((char const   */* __restrict  */)"Setting master gain to 75%% ... ");
#line 205
    fflush(stdout);
#line 206
    tmp___4 = write(fd___0, (void const   *)(& gain), sizeof(gain));
    }
#line 206
    if ((unsigned long )tmp___4 != sizeof(gain)) {
      {
#line 207
      perror("Error:");
      }
    } else {
      {
#line 209
      printf((char const   */* __restrict  */)"OK\n");
      }
    }
  }
  {
#line 214
  memset((void *)(& effects[0]), 0, sizeof(effects[0]));
#line 215
  effects[0].type = (__u16 )81;
#line 216
  effects[0].id = (__s16 )-1;
#line 217
  effects[0].u.periodic.waveform = (__u16 )90;
#line 218
  effects[0].u.periodic.period = (__u16 )10;
#line 219
  effects[0].u.periodic.magnitude = (__s16 )32767;
#line 220
  effects[0].u.periodic.offset = (__s16 )0;
#line 221
  effects[0].u.periodic.phase = (__u16 )0;
#line 222
  effects[0].direction = (__u16 )16384;
#line 223
  effects[0].u.periodic.envelope.attack_length = (__u16 )1000;
#line 224
  effects[0].u.periodic.envelope.attack_level = (__u16 )32767;
#line 225
  effects[0].u.periodic.envelope.fade_length = (__u16 )1000;
#line 226
  effects[0].u.periodic.envelope.fade_level = (__u16 )32767;
#line 227
  effects[0].trigger.button = (__u16 )0;
#line 228
  effects[0].trigger.interval = (__u16 )0;
#line 229
  effects[0].replay.length = (__u16 )20000;
#line 230
  effects[0].replay.delay = (__u16 )1000;
#line 232
  printf((char const   */* __restrict  */)"Uploading effect #0 (Periodic sinusoidal) ... ");
#line 233
  fflush(stdout);
#line 234
  tmp___5 = ioctl(fd___0, (unsigned long )(((1U << 30) | (unsigned int )(69 << 8)) | 128U) | (sizeof(struct ff_effect ) << 16),
                  & effects[0]);
  }
#line 234
  if (tmp___5 == -1) {
    {
#line 235
    perror("Error:");
    }
  } else {
    {
#line 237
    printf((char const   */* __restrict  */)"OK (id %d)\n", (int )effects[0].id);
    }
  }
  {
#line 241
  effects[1].type = (__u16 )82;
#line 242
  effects[1].id = (__s16 )-1;
#line 243
  effects[1].u.constant.level = (__s16 )8192;
#line 244
  effects[1].direction = (__u16 )24576;
#line 245
  effects[1].u.constant.envelope.attack_length = (__u16 )1000;
#line 246
  effects[1].u.constant.envelope.attack_level = (__u16 )4096;
#line 247
  effects[1].u.constant.envelope.fade_length = (__u16 )1000;
#line 248
  effects[1].u.constant.envelope.fade_level = (__u16 )4096;
#line 249
  effects[1].trigger.button = (__u16 )0;
#line 250
  effects[1].trigger.interval = (__u16 )0;
#line 251
  effects[1].replay.length = (__u16 )20000;
#line 252
  effects[1].replay.delay = (__u16 )0;
#line 254
  printf((char const   */* __restrict  */)"Uploading effect #1 (Constant) ... ");
#line 255
  fflush(stdout);
#line 256
  tmp___6 = ioctl(fd___0, (unsigned long )(((1U << 30) | (unsigned int )(69 << 8)) | 128U) | (sizeof(struct ff_effect ) << 16),
                  & effects[1]);
  }
#line 256
  if (tmp___6 == -1) {
    {
#line 257
    perror("Error");
    }
  } else {
    {
#line 259
    printf((char const   */* __restrict  */)"OK (id %d)\n", (int )effects[1].id);
    }
  }
  {
#line 263
  effects[2].type = (__u16 )83;
#line 264
  effects[2].id = (__s16 )-1;
#line 265
  effects[2].u.condition[0].right_saturation = (__u16 )32767;
#line 266
  effects[2].u.condition[0].left_saturation = (__u16 )32767;
#line 267
  effects[2].u.condition[0].right_coeff = (__s16 )8192;
#line 268
  effects[2].u.condition[0].left_coeff = (__s16 )8192;
#line 269
  effects[2].u.condition[0].deadband = (__u16 )0;
#line 270
  effects[2].u.condition[0].center = (__s16 )0;
#line 271
  effects[2].u.condition[1] = effects[2].u.condition[0];
#line 272
  effects[2].trigger.button = (__u16 )0;
#line 273
  effects[2].trigger.interval = (__u16 )0;
#line 274
  effects[2].replay.length = (__u16 )20000;
#line 275
  effects[2].replay.delay = (__u16 )0;
#line 277
  printf((char const   */* __restrict  */)"Uploading effect #2 (Spring) ... ");
#line 278
  fflush(stdout);
#line 279
  tmp___7 = ioctl(fd___0, (unsigned long )(((1U << 30) | (unsigned int )(69 << 8)) | 128U) | (sizeof(struct ff_effect ) << 16),
                  & effects[2]);
  }
#line 279
  if (tmp___7 == -1) {
    {
#line 280
    perror("Error");
    }
  } else {
    {
#line 282
    printf((char const   */* __restrict  */)"OK (id %d)\n", (int )effects[2].id);
    }
  }
  {
#line 286
  effects[3].type = (__u16 )85;
#line 287
  effects[3].id = (__s16 )-1;
#line 288
  effects[3].u.condition[0].right_saturation = (__u16 )32767;
#line 289
  effects[3].u.condition[0].left_saturation = (__u16 )32767;
#line 290
  effects[3].u.condition[0].right_coeff = (__s16 )8192;
#line 291
  effects[3].u.condition[0].left_coeff = (__s16 )8192;
#line 292
  effects[3].u.condition[0].deadband = (__u16 )0;
#line 293
  effects[3].u.condition[0].center = (__s16 )0;
#line 294
  effects[3].u.condition[1] = effects[3].u.condition[0];
#line 295
  effects[3].trigger.button = (__u16 )0;
#line 296
  effects[3].trigger.interval = (__u16 )0;
#line 297
  effects[3].replay.length = (__u16 )20000;
#line 298
  effects[3].replay.delay = (__u16 )0;
#line 300
  printf((char const   */* __restrict  */)"Uploading effect #3 (Damper) ... ");
#line 301
  fflush(stdout);
#line 302
  tmp___8 = ioctl(fd___0, (unsigned long )(((1U << 30) | (unsigned int )(69 << 8)) | 128U) | (sizeof(struct ff_effect ) << 16),
                  & effects[3]);
  }
#line 302
  if (tmp___8 == -1) {
    {
#line 303
    perror("Error");
    }
  } else {
    {
#line 305
    printf((char const   */* __restrict  */)"OK (id %d)\n", (int )effects[3].id);
    }
  }
  {
#line 309
  effects[4].type = (__u16 )80;
#line 310
  effects[4].id = (__s16 )-1;
#line 311
  effects[4].u.rumble.strong_magnitude = (__u16 )32768;
#line 312
  effects[4].u.rumble.weak_magnitude = (__u16 )0;
#line 313
  effects[4].replay.length = (__u16 )5000;
#line 314
  effects[4].replay.delay = (__u16 )1000;
#line 316
  printf((char const   */* __restrict  */)"Uploading effect #4 (Strong rumble, with heavy motor) ... ");
#line 317
  fflush(stdout);
#line 318
  tmp___9 = ioctl(fd___0, (unsigned long )(((1U << 30) | (unsigned int )(69 << 8)) | 128U) | (sizeof(struct ff_effect ) << 16),
                  & effects[4]);
  }
#line 318
  if (tmp___9 == -1) {
    {
#line 319
    perror("Error");
    }
  } else {
    {
#line 321
    printf((char const   */* __restrict  */)"OK (id %d)\n", (int )effects[4].id);
    }
  }
  {
#line 325
  effects[5].type = (__u16 )80;
#line 326
  effects[5].id = (__s16 )-1;
#line 327
  effects[5].u.rumble.strong_magnitude = (__u16 )0;
#line 328
  effects[5].u.rumble.weak_magnitude = (__u16 )49152;
#line 329
  effects[5].replay.length = (__u16 )5000;
#line 330
  effects[5].replay.delay = (__u16 )0;
#line 332
  printf((char const   */* __restrict  */)"Uploading effect #5 (Weak rumble, with light motor) ... ");
#line 333
  fflush(stdout);
#line 334
  tmp___10 = ioctl(fd___0, (unsigned long )(((1U << 30) | (unsigned int )(69 << 8)) | 128U) | (sizeof(struct ff_effect ) << 16),
                   & effects[5]);
  }
#line 334
  if (tmp___10 == -1) {
    {
#line 335
    perror("Error");
    }
  } else {
    {
#line 337
    printf((char const   */* __restrict  */)"OK (id %d)\n", (int )effects[5].id);
    }
  }
  {
#line 342
  while (1) {
    while_continue___3: /* CIL Label */ ;
    {
#line 343
    printf((char const   */* __restrict  */)"Enter effect number, -1 to exit\n");
#line 344
    i = -1;
#line 345
    tmp___12 = scanf((char const   */* __restrict  */)"%d", & i);
    }
#line 345
    if (tmp___12 == -1) {
      {
#line 346
      printf((char const   */* __restrict  */)"Read error\n");
      }
    } else
#line 348
    if (i >= 0) {
#line 348
      if (i < 6) {
        {
#line 349
        memset((void *)(& play), 0, sizeof(play));
#line 350
        play.type = (__u16 )21;
#line 351
        play.code = (__u16 )effects[i].id;
#line 352
        play.value = 1;
#line 354
        tmp___11 = write(fd___0, (void const   *)(& play), sizeof(play));
        }
#line 354
        if (tmp___11 == -1L) {
          {
#line 355
          perror("Play effect");
#line 356
          exit(1);
          }
        }
        {
#line 359
        printf((char const   */* __restrict  */)"Now Playing: %s\n", effect_names[i]);
        }
      } else {
#line 348
        goto _L;
      }
    } else
    _L: 
#line 361
    if (i == -2) {
      {
#line 363
      i___0 = *((int *)0);
#line 364
      printf((char const   */* __restrict  */)"Crash test: %d\n", i___0);
      }
    } else
#line 366
    if (i != -1) {
      {
#line 367
      printf((char const   */* __restrict  */)"No such effect\n");
      }
    }
#line 342
    if (! (i >= 0)) {
#line 342
      goto while_break___3;
    }
  }
  while_break___9: /* CIL Label */ ;
  }
  while_break___3: 
  {
#line 372
  printf((char const   */* __restrict  */)"Stopping effects\n");
#line 373
  i = 0;
  }
  {
#line 373
  while (1) {
    while_continue___4: /* CIL Label */ ;

#line 373
    if (! (i < 6)) {
#line 373
      goto while_break___4;
    }
    {
#line 374
    memset((void *)(& stop), 0, sizeof(stop));
#line 375
    stop.type = (__u16 )21;
#line 376
    stop.code = (__u16 )effects[i].id;
#line 377
    stop.value = 0;
#line 379
    tmp___13 = write(fd___0, (void const   *)(& stop), sizeof(stop));
    }
#line 379
    if (tmp___13 == -1L) {
      {
#line 380
      perror("");
#line 381
      exit(1);
      }
    }
#line 373
    i ++;
  }
  while_break___10: /* CIL Label */ ;
  }
  while_break___4: 
  {
#line 386
  exit(0);
  }
}
}
#line 50 "/usr/include/x86_64-linux-gnu/bits/errno.h"
extern  __attribute__((__nothrow__)) int *( __attribute__((__leaf__)) __errno_location)(void)  __attribute__((__const__)) ;
#line 170 "/usr/include/stdio.h"
extern struct _IO_FILE *stderr ;
#line 356
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
#line 695
extern int puts(char const   *__s ) ;
#line 106 "/usr/include/x86_64-linux-gnu/sys/select.h"
extern int select(int __nfds , fd_set * __restrict  __readfds , fd_set * __restrict  __writefds ,
                  fd_set * __restrict  __exceptfds , struct timeval * __restrict  __timeout ) ;
#line 342 "/usr/include/string.h"
extern  __attribute__((__nothrow__)) char *( __attribute__((__nonnull__(1,2), __leaf__)) strstr)(char const   *__haystack ,
                                                                                                 char const   *__needle )  __attribute__((__pure__)) ;
#line 360 "/usr/include/unistd.h"
extern ssize_t read(int __fd , void *__buf , size_t __nbytes ) ;
#line 45 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/axbtnmap.h"
int getaxmap(int fd___0 , uint8_t *axmap___0 ) ;
#line 50
int setaxmap(int fd___0 , uint8_t *axmap___0 ) ;
#line 57
int getbtnmap(int fd___0 , uint16_t *btnmap ) ;
#line 62
int setbtnmap(int fd___0 , uint16_t *btnmap ) ;
#line 37 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/axbtnmap.c"
int determine_ioctl(int fd___0 , int *ioctls , int *ioctl_used , void *argp ) 
{ 
  int i ;
  int retval ;
  int *tmp ;

  {
#line 39
  retval = 0;
#line 42
  i = 0;
  {
#line 42
  while (1) {
    while_continue: /* CIL Label */ ;

#line 42
    if (! *(ioctls + i)) {
#line 42
      goto while_break;
    }
    {
#line 43
    retval = ioctl(fd___0, (unsigned long )*(ioctls + i), argp);
    }
#line 43
    if (retval >= 0) {
#line 45
      *ioctl_used = *(ioctls + i);
#line 46
      return (retval);
    } else {
      {
#line 47
      tmp = __errno_location();
      }
#line 47
      if (*tmp != -22) {
#line 49
        return (retval);
      }
    }
#line 42
    i ++;
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: ;
#line 52
  return (retval);
}
}
#line 57 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/axbtnmap.c"
static int jsiocgbtnmap  =    0;
#line 55 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/axbtnmap.c"
int getbtnmap(int fd___0 , uint16_t *btnmap ) 
{ 
  int ioctls[4] ;
  int tmp ;
  int tmp___0 ;
  void *__cil_tmp6 ;

  {
#line 58
  ioctls[0] = (int )((unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 52U) | (sizeof(__u16 [512]) << 16));
#line 58
  ioctls[1] = (int )((unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 52U) | (sizeof(__u16 [512]) << 16));
#line 58
  ioctls[2] = (int )((unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 52U) | (sizeof(__u16 [256]) << 16));
#line 58
  ioctls[3] = 0;
#line 60
  if (jsiocgbtnmap != 0) {
    {
#line 62
    tmp = ioctl(fd___0, (unsigned long )jsiocgbtnmap, btnmap);
    }
#line 62
    return (tmp);
  } else {
    {
#line 64
    tmp___0 = determine_ioctl(fd___0, ioctls, & jsiocgbtnmap, (void *)btnmap);
    }
#line 64
    return (tmp___0);
  }
}
}
#line 70 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/axbtnmap.c"
static int jsiocsbtnmap  =    0;
#line 68 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/axbtnmap.c"
int setbtnmap(int fd___0 , uint16_t *btnmap ) 
{ 
  int ioctls[4] ;
  int tmp ;
  int tmp___0 ;
  void *__cil_tmp6 ;

  {
#line 71
  ioctls[0] = (int )((unsigned long )(((1U << 30) | (unsigned int )(106 << 8)) | 51U) | (sizeof(__u16 [512]) << 16));
#line 71
  ioctls[1] = (int )((unsigned long )(((1U << 30) | (unsigned int )(106 << 8)) | 51U) | (sizeof(__u16 [512]) << 16));
#line 71
  ioctls[2] = (int )((unsigned long )(((1U << 30) | (unsigned int )(106 << 8)) | 51U) | (sizeof(__u16 [256]) << 16));
#line 71
  ioctls[3] = 0;
#line 73
  if (jsiocsbtnmap != 0) {
    {
#line 75
    tmp = ioctl(fd___0, (unsigned long )jsiocsbtnmap, btnmap);
    }
#line 75
    return (tmp);
  } else {
    {
#line 77
    tmp___0 = determine_ioctl(fd___0, ioctls, & jsiocsbtnmap, (void *)btnmap);
    }
#line 77
    return (tmp___0);
  }
}
}
#line 81 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/axbtnmap.c"
int getaxmap(int fd___0 , uint8_t *axmap___0 ) 
{ 
  int tmp ;

  {
  {
#line 83
  tmp = ioctl(fd___0, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 50U) | (sizeof(__u8 [64]) << 16),
              axmap___0);
  }
#line 83
  return (tmp);
}
}
#line 86 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/axbtnmap.c"
int setaxmap(int fd___0 , uint8_t *axmap___0 ) 
{ 
  int tmp ;

  {
  {
#line 88
  tmp = ioctl(fd___0, (unsigned long )(((1U << 30) | (unsigned int )(106 << 8)) | 49U) | (sizeof(__u8 [64]) << 16),
              axmap___0);
  }
#line 88
  return (tmp);
}
}
#line 71 "/usr/include/x86_64-linux-gnu/sys/time.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) gettimeofday)(struct timeval * __restrict  __tv ,
                                                                                                   __timezone_ptr_t __tz ) ;
#line 137 "/usr/include/fcntl.h"
extern int fcntl(int __fd , int __cmd  , ...) ;
#line 433 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) sscanf)(char const   * __restrict  __s ,
                                                                             char const   * __restrict  __format 
                                                                             , ...)  __asm__("__isoc99_sscanf")  ;
#line 580
extern int putchar(int __c ) ;
#line 689
extern int fputs(char const   * __restrict  __s , FILE * __restrict  __stream ) ;
#line 279 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h"
extern  __attribute__((__nothrow__)) double ( __attribute__((__leaf__)) rint)(double __x ) ;
#line 49 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
char const   *pos_name[3]  = {      "minimum",      "center",      "maximum"};
#line 50 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
char const   *corr_name[2]  = {      "none (raw)",      "broken line"};
#line 51 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
char const   corr_coef_num[2]  = {      (char const   )0,      (char const   )4};
#line 58 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
int fd  ;
#line 59 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
struct js_corr corr[64]  ;
#line 60 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
__u8 axmap[64]  ;
#line 61 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
__u8 axmap2[64]  ;
#line 62 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
__u16 buttonmap[512]  ;
#line 63 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
char axes  ;
#line 63 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
char buttons  ;
#line 63 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
char fuzz  ;
#line 64 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
int version  ;
#line 65 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
struct correction_data corda[64]  ;
#line 67 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
struct js_info js  ;
#line 72 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
void print_position(int i , int a ) 
{ 
  char *__cil_tmp3 ;

  {
  {
#line 74
  printf((char const   */* __restrict  */)"Axis %d: %8d\r", i, a);
#line 75
  fflush(stdout);
  }
#line 77
  return;
}
}
#line 79 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
int get_time(void) 
{ 
  struct timeval tv ;

  {
  {
#line 83
  gettimeofday((struct timeval */* __restrict  */)(& tv), (__timezone_ptr_t )((void *)0));
  }
#line 85
  return ((int )(tv.tv_sec * 1000L + tv.tv_usec / 1000L));
}
}
#line 88 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
void wait_for_event(int d , struct js_info *s ) 
{ 
  struct js_event ev ;
  struct timeval tv ;
  char buf ;
  fd_set set ;
  int __d0 ;
  int __d1 ;
  ssize_t tmp ;
  int tmp___0 ;
  void *__cil_tmp11 ;

  {
#line 95
  tv.tv_sec = (__time_t )0;
#line 96
  tv.tv_usec = (__suseconds_t )100000;
  {
#line 98
  while (1) {
    while_continue: /* CIL Label */ ;
#line 98
    __asm__  volatile   ("cld; rep; "
                         "stosq": "=c" (__d0), "=D" (__d1): "a" (0), "0" (sizeof(fd_set ) / sizeof(__fd_mask )),
                         "1" (& set.__fds_bits[0]): "memory");
#line 98
    goto while_break;
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: 
  {
#line 99
  set.__fds_bits[0 / (8 * (int )sizeof(__fd_mask ))] |= 1L << 0 % (8 * (int )sizeof(__fd_mask ));
#line 100
  set.__fds_bits[d / (8 * (int )sizeof(__fd_mask ))] |= 1L << d % (8 * (int )sizeof(__fd_mask ));
#line 102
  tmp___0 = select(d + 1, (fd_set */* __restrict  */)(& set), (fd_set */* __restrict  */)((fd_set *)((void *)0)),
                   (fd_set */* __restrict  */)((fd_set *)((void *)0)), (struct timeval */* __restrict  */)(& tv));
  }
#line 102
  if (tmp___0) {
#line 104
    if ((set.__fds_bits[d / (8 * (int )sizeof(__fd_mask ))] & (1L << d % (8 * (int )sizeof(__fd_mask )))) != 0L) {
      {
#line 105
      tmp = read(d, (void *)(& ev), sizeof(struct js_event ));
      }
#line 105
      if ((unsigned long )tmp == sizeof(struct js_event )) {
#line 107
        if (((int )ev.type & -129) == 2) {
#line 107
          goto case_2;
        }
#line 109
        if (((int )ev.type & -129) == 1) {
#line 109
          goto case_1;
        }
#line 106
        goto switch_break;
        case_2: 
#line 108
        s->axis[ev.number] = (int )ev.value;
#line 108
        goto switch_break;
        case_1: 
#line 110
        s->buttons = (s->buttons & ~ (1 << (int )ev.number)) | ((int )ev.value << (int )ev.number);
        switch_break: ;
      }
    }
#line 114
    if ((set.__fds_bits[0 / (8 * (int )sizeof(__fd_mask ))] & (1L << 0 % (8 * (int )sizeof(__fd_mask )))) != 0L) {
      {
#line 115
      read(0, (void *)(& buf), (size_t )1);
#line 116
      s->buttons |= 1 << 31;
      }
    }
  } else {
#line 120
    s->buttons &= ~ (1 << 31);
  }
#line 122
  return;
}
}
#line 124 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
void putcs(char *s ) 
{ 
  int i ;

  {
  {
#line 127
  putchar('\r');
#line 128
  i = 0;
  }
  {
#line 128
  while (1) {
    while_continue: /* CIL Label */ ;

#line 128
    if (! (i < 78)) {
#line 128
      goto while_break;
    }
    {
#line 128
    putchar(' ');
#line 128
    i ++;
    }
  }
  while_break___0: /* CIL Label */ ;
  }
  while_break: 
  {
#line 129
  putchar('\r');
#line 130
  fputs((char const   */* __restrict  */)((char const   *)s), (FILE */* __restrict  */)stdout);
#line 131
  fflush(stdout);
  }
#line 132
  return;
}
}
#line 134 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
int solve_broken(int *results , struct correction_data inputs ) 
{ 
  double a ;
  double b ;
  double c ;
  double d ;
  double tmp ;
  double tmp___0 ;
  double tmp___1 ;
  double tmp___2 ;

  {
  {
#line 138
  a = (double )inputs.cmin[1];
#line 139
  b = (double )inputs.cmax[1];
#line 140
  c = 32767.0 / (double )(inputs.cmin[1] - inputs.cmax[0]);
#line 141
  d = 32767.0 / (double )(inputs.cmin[2] - inputs.cmax[1]);
#line 143
  tmp = rint(a);
#line 143
  *(results + 0) = (int )tmp;
#line 144
  tmp___0 = rint(b);
#line 144
  *(results + 1) = (int )tmp___0;
#line 145
  tmp___1 = rint(c * 16384.0);
#line 145
  *(results + 2) = (int )tmp___1;
#line 146
  tmp___2 = rint(d * 16384.0);
#line 146
  *(results + 3) = (int )tmp___2;
  }
#line 148
  return (1);
}
}
#line 151 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
void help(void) 
{ 
  char *__cil_tmp1 ;
  char *__cil_tmp2 ;
  char *__cil_tmp3 ;
  char *__cil_tmp4 ;
  char *__cil_tmp5 ;
  char *__cil_tmp6 ;
  char *__cil_tmp7 ;
  char *__cil_tmp8 ;
  char *__cil_tmp9 ;
  char *__cil_tmp10 ;
  char *__cil_tmp11 ;
  char *__cil_tmp12 ;
  char *__cil_tmp13 ;
  char *__cil_tmp14 ;
  char *__cil_tmp15 ;
  char *__cil_tmp16 ;

  {
  {
#line 153
  putchar('\n');
#line 154
  puts("Usage: jscal <device>");
#line 155
  putchar('\n');
#line 156
  puts("  -c             --calibrate         Calibrate the joystick");
#line 157
  puts("  -h             --help              Display this help");
#line 158
  puts("  -s <x,y,z...>  --set-correction    Sets correction to specified values");
#line 159
  puts("  -t             --test-center       Tests if joystick is corectly calibrated");
#line 160
  puts("                                       returns 0 on success, see the jscal");
#line 161
  puts("                                       manpage for error values");
#line 162
  puts("  -V             --version           Prints the version numbers");
#line 163
  puts("  -p             --print-correction  Prints the current settings as a jscal");
#line 164
  puts("                                       command line");
#line 165
  puts("  -q             --print-mappings    Print the current axis and button");
#line 166
  puts("                                       mappings as a jscal command line");
#line 167
  puts("  -u <n_of_axes,axmap1,axmap2,...,");
#line 168
  puts("      n_of_buttons,btnmap1,btnmap2,");
#line 169
  puts("      ...>       --set-mappings      Sets axis and button mappings to the");
#line 170
  puts("                                        specified values");
#line 171
  putchar('\n');
  }
#line 172
  return;
}
}
#line 174 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
void print_info(void) 
{ 
  int i ;
  int j ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  char *__cil_tmp6 ;
  char *__cil_tmp7 ;
  char *__cil_tmp8 ;
  char *__cil_tmp9 ;
  char *__cil_tmp10 ;
  char *__cil_tmp11 ;
  char *__cil_tmp12 ;

  {
  {
#line 178
  tmp = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 17U) | (sizeof(__u8 ) << 16),
              & axes);
  }
#line 178
  if (tmp < 0) {
    {
#line 179
    perror("jscal: error getting axes");
#line 180
    exit(1);
    }
  }
  {
#line 182
  tmp___0 = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 18U) | (sizeof(__u8 ) << 16),
                  & buttons);
  }
#line 182
  if (tmp___0 < 0) {
    {
#line 183
    perror("jscal: error getting buttons");
#line 184
    exit(1);
    }
  }
  {
#line 186
  tmp___1 = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 34U) | (sizeof(struct js_corr ) << 16),
                  & corr);
  }
#line 186
  if (tmp___1 < 0) {
    {
#line 187
    perror("jscal: error getting correction");
#line 188
    exit(1);
    }
  }
  {
#line 191
  printf((char const   */* __restrict  */)"Joystick has %d axes and %d buttons.\n",
         (int )axes, (int )buttons);
#line 192
  i = 0;
  }
  {
#line 192
  while (1) {
    while_continue: /* CIL Label */ ;

#line 192
    if (! (i < (int )axes)) {
#line 192
      goto while_break;
    }
    {
#line 193
    printf((char const   */* __restrict  */)"Correction for axis %d is %s, precision is %d.\n",
           i, corr_name[(int )corr[i].type], (int )corr[i].prec);
    }
#line 195
    if (corr_coef_num[(int )corr[i].type]) {
      {
#line 196
      printf((char const   */* __restrict  */)"Coeficients are:");
#line 197
      j = 0;
      }
      {
#line 197
      while (1) {
        while_continue___0: /* CIL Label */ ;

#line 197
        if (! (j < (int )corr_coef_num[(int )corr[i].type])) {
#line 197
          goto while_break___0;
        }
        {
#line 198
        printf((char const   */* __restrict  */)" %d", corr[i].coef[j]);
        }
#line 199
        if (j < (int )((int const   )corr_coef_num[(int )corr[i].type] - 1)) {
          {
#line 199
          putchar(',');
          }
        }
#line 197
        j ++;
      }
      while_break___2: /* CIL Label */ ;
      }
      while_break___0: 
      {
#line 201
      putchar('\n');
      }
    }
#line 192
    i ++;
  }
  while_break___1: /* CIL Label */ ;
  }
  while_break: 
  {
#line 204
  putchar('\n');
  }
#line 205
  return;
}
}
#line 207 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
void calibrate(void) 
{ 
  int i ;
  int j ;
  int t ;
  int b ;
  int axis ;
  int pos ;
  int tmp ;
  int i___0 ;
  int amax[64] ;
  int amin[64] ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  void *__cil_tmp16 ;
  void *__cil_tmp17 ;
  char *__cil_tmp18 ;
  char *__cil_tmp19 ;
  char *__cil_tmp20 ;
  char *__cil_tmp21 ;
  char *__cil_tmp22 ;
  char *__cil_tmp23 ;
  char *__cil_tmp24 ;
  char *__cil_tmp25 ;
  char *__cil_tmp26 ;
  char *__cil_tmp27 ;
  char *__cil_tmp28 ;
  char *__cil_tmp29 ;
  char *__cil_tmp30 ;
  char *__cil_tmp31 ;
  char *__cil_tmp32 ;
  char *__cil_tmp33 ;

  {
#line 212
  i = 0;
  {
#line 212
  while (1) {
    while_continue: /* CIL Label */ ;

#line 212
    if (! (i < 64)) {
#line 212
      goto while_break;
    }
#line 213
    corr[i].type = (__u16 )0;
#line 214
    corr[i].prec = (__s16 )0;
#line 212
    i ++;
  }
  while_break___13: /* CIL Label */ ;
  }
  while_break: 
  {
#line 217
  tmp = ioctl(fd, (unsigned long )(((1U << 30) | (unsigned int )(106 << 8)) | 33U) | (sizeof(struct js_corr ) << 16),
              & corr);
  }
#line 217
  if (tmp < 0) {
    {
#line 218
    perror("jscal: error setting correction");
#line 219
    exit(1);
    }
  }
  {
#line 227
  puts("Calibrating precision: wait and don\'t touch the joystick.");
#line 229
  wait_for_event(fd, & js);
#line 230
  t = get_time();
  }
  {
#line 231
  while (1) {
    while_continue___0: /* CIL Label */ ;
    {
#line 231
    tmp___0 = get_time();
    }
#line 231
    if (! (tmp___0 < t + 50)) {
#line 231
      goto while_break___0;
    }
    {
#line 231
    wait_for_event(fd, & js);
    }
  }
  while_break___14: /* CIL Label */ ;
  }
  while_break___0: 
  {
#line 233
  wait_for_event(fd, & js);
#line 234
  t = get_time();
#line 235
  i___0 = 0;
  }
  {
#line 235
  while (1) {
    while_continue___1: /* CIL Label */ ;

#line 235
    if (! (i___0 < (int )axes)) {
#line 235
      goto while_break___1;
    }
#line 236
    tmp___1 = js.axis[i___0];
#line 236
    amax[i___0] = tmp___1;
#line 236
    amin[i___0] = tmp___1;
#line 235
    i___0 ++;
  }
  while_break___15: /* CIL Label */ ;
  }
  while_break___1: ;
  {
#line 238
  while (1) {
    while_continue___2: /* CIL Label */ ;
    {
#line 239
    wait_for_event(fd, & js);
#line 240
    i___0 = 0;
    }
    {
#line 240
    while (1) {
      while_continue___3: /* CIL Label */ ;

#line 240
      if (! (i___0 < (int )axes)) {
#line 240
        goto while_break___3;
      }
#line 241
      if (amin[i___0] > js.axis[i___0]) {
        {
#line 242
        amin[i___0] = js.axis[i___0];
#line 243
        t = get_time();
        }
      }
#line 245
      if (amax[i___0] < js.axis[i___0]) {
        {
#line 246
        amax[i___0] = js.axis[i___0];
#line 247
        t = get_time();
        }
      }
      {
#line 249
      printf((char const   */* __restrict  */)"Axis %d:%5d,%5d ", i___0, amin[i___0],
             amax[i___0]);
#line 240
      i___0 ++;
      }
    }
    while_break___17: /* CIL Label */ ;
    }
    while_break___3: 
    {
#line 251
    printf((char const   */* __restrict  */)"\r");
#line 252
    fflush(stdout);
#line 238
    tmp___2 = get_time();
    }
#line 238
    if (! (tmp___2 < t + 4000)) {
#line 238
      goto while_break___2;
    }
  }
  while_break___16: /* CIL Label */ ;
  }
  while_break___2: 
  {
#line 255
  printf((char const   */* __restrict  */)"Done. Precision is:                                             \n");
#line 257
  i___0 = 0;
  }
  {
#line 257
  while (1) {
    while_continue___4: /* CIL Label */ ;

#line 257
    if (! (i___0 < (int )axes)) {
#line 257
      goto while_break___4;
    }
    {
#line 258
    corr[i___0].prec = (__s16 )(amax[i___0] - amin[i___0]);
#line 259
    printf((char const   */* __restrict  */)"Axis: %d: %5d\n", i___0, (int )corr[i___0].prec);
#line 257
    i___0 ++;
    }
  }
  while_break___18: /* CIL Label */ ;
  }
  while_break___4: 
  {
#line 262
  puts("");
#line 267
  b = js.buttons;
#line 269
  axis = 0;
  }
  {
#line 269
  while (1) {
    while_continue___5: /* CIL Label */ ;

#line 269
    if (! (axis < (int )axes)) {
#line 269
      goto while_break___5;
    }
#line 270
    pos = 0;
    {
#line 270
    while (1) {
      while_continue___6: /* CIL Label */ ;

#line 270
      if (! (pos < 3)) {
#line 270
        goto while_break___6;
      }
      {
#line 271
      while (1) {
        while_continue___7: /* CIL Label */ ;

#line 271
        if (! (b ^ js.buttons)) {
#line 271
          goto while_break___7;
        }
        {
#line 271
        wait_for_event(fd, & js);
        }
      }
      while_break___21: /* CIL Label */ ;
      }
      while_break___7: 
      {
#line 272
      printf((char const   */* __restrict  */)"Move axis %d to %s position and push any button.\n",
             axis, pos_name[pos]);
      }
      {
#line 274
      while (1) {
        while_continue___8: /* CIL Label */ ;

#line 274
        if (! (! (b ^ js.buttons))) {
#line 274
          goto while_break___8;
        }
        {
#line 275
        print_position(axis, js.axis[axis]);
#line 276
        wait_for_event(fd, & js);
        }
      }
      while_break___22: /* CIL Label */ ;
      }
      while_break___8: 
      {
#line 279
      putcs((char *)"Hold ... ");
#line 281
      corda[axis].cmin[pos] = js.axis[axis];
#line 282
      corda[axis].cmax[pos] = js.axis[axis];
#line 284
      t = get_time();
      }
      {
#line 286
      while (1) {
        while_continue___9: /* CIL Label */ ;
        {
#line 286
        tmp___3 = get_time();
        }
#line 286
        if (tmp___3 < t + 2000) {
#line 286
          if (! (b ^ js.buttons)) {
#line 286
            goto while_break___9;
          }
        } else {
#line 286
          goto while_break___9;
        }
#line 287
        if (js.axis[axis] < corda[axis].cmin[pos]) {
          {
#line 288
          corda[axis].cmin[pos] = js.axis[axis];
#line 289
          t = get_time();
          }
        }
#line 291
        if (js.axis[axis] > corda[axis].cmax[pos]) {
          {
#line 292
          corda[axis].cmax[pos] = js.axis[axis];
#line 293
          t = get_time();
          }
        }
        {
#line 295
        wait_for_event(fd, & js);
        }
      }
      while_break___23: /* CIL Label */ ;
      }
      while_break___9: 
      {
#line 297
      puts("OK.");
#line 270
      pos ++;
      }
    }
    while_break___20: /* CIL Label */ ;
    }
    while_break___6: 
#line 269
    axis ++;
  }
  while_break___19: /* CIL Label */ ;
  }
  while_break___5: 
  {
#line 300
  puts("");
#line 302
  j = 0;
  }
  {
#line 302
  while (1) {
    while_continue___10: /* CIL Label */ ;

#line 302
    if (! (j < (int )axes)) {
#line 302
      goto while_break___10;
    }
    {
#line 303
    solve_broken(corr[j].coef, corda[j]);
#line 304
    corr[j].type = (__u16 )1;
#line 302
    j ++;
    }
  }
  while_break___24: /* CIL Label */ ;
  }
  while_break___10: 
  {
#line 307
  puts("Setting correction to:");
#line 308
  i = 0;
  }
  {
#line 308
  while (1) {
    while_continue___11: /* CIL Label */ ;

#line 308
    if (! (i < (int )axes)) {
#line 308
      goto while_break___11;
    }
    {
#line 309
    printf((char const   */* __restrict  */)"Correction for axis %d: %s, precision: %d.\n",
           i, corr_name[(int )corr[i].type], (int )corr[i].prec);
    }
#line 311
    if (corr_coef_num[(int )corr[i].type]) {
      {
#line 312
      printf((char const   */* __restrict  */)"Coeficients:");
#line 313
      j = 0;
      }
      {
#line 313
      while (1) {
        while_continue___12: /* CIL Label */ ;

#line 313
        if (! (j < (int )corr_coef_num[(int )corr[i].type])) {
#line 313
          goto while_break___12;
        }
        {
#line 314
        printf((char const   */* __restrict  */)" %d", corr[i].coef[j]);
        }
#line 315
        if (j < (int )((int const   )corr_coef_num[(int )corr[i].type] - 1)) {
          {
#line 315
          putchar(',');
          }
        }
#line 313
        j ++;
      }
      while_break___26: /* CIL Label */ ;
      }
      while_break___12: 
      {
#line 317
      putchar('\n');
      }
    }
#line 308
    i ++;
  }
  while_break___25: /* CIL Label */ ;
  }
  while_break___11: 
  {
#line 321
  putchar('\n');
#line 323
  tmp___4 = ioctl(fd, (unsigned long )(((1U << 30) | (unsigned int )(106 << 8)) | 33U) | (sizeof(struct js_corr ) << 16),
                  & corr);
  }
#line 323
  if (tmp___4 < 0) {
    {
#line 324
    perror("jscal: error setting correction");
#line 325
    exit(1);
    }
  }
#line 327
  return;
}
}
#line 329 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
void print_version(void) 
{ 
  char *__cil_tmp1 ;
  char *__cil_tmp2 ;

  {
  {
#line 331
  printf((char const   */* __restrict  */)"JsCal was compiled for driver version: %d.%d.%d\n",
         131328 >> 16, (131328 >> 8) & 255, 0);
#line 333
  printf((char const   */* __restrict  */)"Current running driver version: %d.%d.%d\n",
         version >> 16, (version >> 8) & 255, version & 255);
  }
#line 335
  return;
}
}
#line 337 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
void print_mappings(char *devicename ) 
{ 
  int i ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  char *__cil_tmp7 ;
  char *__cil_tmp8 ;
  char *__cil_tmp9 ;
  char *__cil_tmp10 ;
  char *__cil_tmp11 ;
  char *__cil_tmp12 ;
  char *__cil_tmp13 ;
  char *__cil_tmp14 ;

  {
  {
#line 341
  tmp = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 17U) | (sizeof(__u8 ) << 16),
              & axes);
  }
#line 341
  if (tmp < 0) {
    {
#line 342
    perror("jscal: error getting axes");
#line 343
    exit(1);
    }
  }
  {
#line 345
  tmp___0 = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 18U) | (sizeof(__u8 ) << 16),
                  & buttons);
  }
#line 345
  if (tmp___0 < 0) {
    {
#line 346
    perror("jscal: error getting buttons");
#line 347
    exit(1);
    }
  }
  {
#line 349
  tmp___1 = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 50U) | (sizeof(__u8 [64]) << 16),
                  & axmap);
  }
#line 349
  if (tmp___1 < 0) {
    {
#line 350
    perror("jscal: error getting axis map");
#line 351
    exit(1);
    }
  }
  {
#line 353
  tmp___2 = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 52U) | (sizeof(__u16 [512]) << 16),
                  & buttonmap);
  }
#line 353
  if (tmp___2 < 0) {
#line 354
    buttons = (char)0;
  }
  {
#line 357
  printf((char const   */* __restrict  */)"jscal -u %d", (int )axes);
#line 358
  i = 0;
  }
  {
#line 358
  while (1) {
    while_continue: /* CIL Label */ ;

#line 358
    if (! (i < (int )axes)) {
#line 358
      goto while_break;
    }
    {
#line 360
    printf((char const   */* __restrict  */)",%d", (int )axmap[i]);
#line 358
    i ++;
    }
  }
  while_break___1: /* CIL Label */ ;
  }
  while_break: 
  {
#line 363
  printf((char const   */* __restrict  */)",%d", (int )buttons);
#line 364
  i = 0;
  }
  {
#line 364
  while (1) {
    while_continue___0: /* CIL Label */ ;

#line 364
    if (! (i < (int )buttons)) {
#line 364
      goto while_break___0;
    }
    {
#line 366
    printf((char const   */* __restrict  */)",%d", (int )buttonmap[i]);
#line 364
    i ++;
    }
  }
  while_break___2: /* CIL Label */ ;
  }
  while_break___0: 
  {
#line 369
  printf((char const   */* __restrict  */)" %s\n", devicename);
  }
#line 370
  return;
}
}
#line 373 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
void get_axmap2(void) 
{ 
  int tmp ;
  char *__cil_tmp2 ;

  {
  {
#line 375
  tmp = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 50U) | (sizeof(__u8 [64]) << 16),
              & axmap2);
  }
#line 375
  if (tmp < 0) {
    {
#line 376
    perror("jscal: error getting axis map");
#line 377
    exit(1);
    }
  }
#line 379
  return;
}
}
#line 385 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
void correct_axes(void) 
{ 
  int axmes[64] ;
  struct js_corr corr_tmp[64] ;
  int i ;
  int *ax ;
  unsigned long __lengthofax ;
  void *tmp ;
  int tmp___0 ;
  int tmp___1 ;
  void *__cil_tmp9 ;
  void *__cil_tmp10 ;
  int __cil_tmp11 ;
  void *__cil_tmp12 ;
  char *__cil_tmp13 ;
  char *__cil_tmp14 ;

  {
  {
#line 390
  __lengthofax = (unsigned long )axes;
#line 390
  tmp = __builtin_alloca(sizeof(*ax) * __lengthofax);
#line 390
  ax = (int *)tmp;
#line 392
  i = 0;
  }
  {
#line 392
  while (1) {
    while_continue: /* CIL Label */ ;

#line 392
    if (! (i < (int )axes)) {
#line 392
      goto while_break;
    }
#line 393
    axmes[axmap2[i]] = i;
#line 392
    i ++;
  }
  while_break___2: /* CIL Label */ ;
  }
  while_break: 
#line 395
  i = 0;
  {
#line 395
  while (1) {
    while_continue___0: /* CIL Label */ ;

#line 395
    if (! (i < (int )axes)) {
#line 395
      goto while_break___0;
    }
#line 396
    *(ax + i) = axmes[axmap[i]];
#line 395
    i ++;
  }
  while_break___3: /* CIL Label */ ;
  }
  while_break___0: 
  {
#line 399
  tmp___0 = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 34U) | (sizeof(struct js_corr ) << 16),
                  & corr);
  }
#line 399
  if (tmp___0 < 0) {
    {
#line 400
    perror("jscal: error getting correction");
#line 401
    exit(1);
    }
  }
#line 404
  i = 0;
  {
#line 404
  while (1) {
    while_continue___1: /* CIL Label */ ;

#line 404
    if (! (i < (int )axes)) {
#line 404
      goto while_break___1;
    }
#line 405
    corr_tmp[i] = corr[*(ax + i)];
#line 404
    i ++;
  }
  while_break___4: /* CIL Label */ ;
  }
  while_break___1: 
  {
#line 407
  tmp___1 = ioctl(fd, (unsigned long )(((1U << 30) | (unsigned int )(106 << 8)) | 33U) | (sizeof(struct js_corr ) << 16),
                  & corr_tmp);
  }
#line 407
  if (tmp___1 < 0) {
    {
#line 408
    perror("jscal: error setting correction");
#line 409
    exit(1);
    }
  }
#line 412
  return;
}
}
#line 414 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
void print_settings(char *devicename ) 
{ 
  int i ;
  int j ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  char *__cil_tmp7 ;
  char *__cil_tmp8 ;
  char *__cil_tmp9 ;
  char *__cil_tmp10 ;
  char *__cil_tmp11 ;
  char *__cil_tmp12 ;
  char *__cil_tmp13 ;

  {
  {
#line 418
  tmp = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 17U) | (sizeof(__u8 ) << 16),
              & axes);
  }
#line 418
  if (tmp < 0) {
    {
#line 419
    perror("jscal: error getting axes");
#line 420
    exit(1);
    }
  }
  {
#line 422
  tmp___0 = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 18U) | (sizeof(__u8 ) << 16),
                  & buttons);
  }
#line 422
  if (tmp___0 < 0) {
    {
#line 423
    perror("jscal: error getting buttons");
#line 424
    exit(1);
    }
  }
  {
#line 426
  tmp___1 = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 34U) | (sizeof(struct js_corr ) << 16),
                  & corr);
  }
#line 426
  if (tmp___1 < 0) {
    {
#line 427
    perror("jscal: error getting correction");
#line 428
    exit(1);
    }
  }
  {
#line 431
  printf((char const   */* __restrict  */)"jscal -s %d", (int )axes);
#line 432
  i = 0;
  }
  {
#line 432
  while (1) {
    while_continue: /* CIL Label */ ;

#line 432
    if (! (i < (int )axes)) {
#line 432
      goto while_break;
    }
    {
#line 433
    printf((char const   */* __restrict  */)",%d,%d", (int )corr[i].type, (int )corr[i].prec);
#line 434
    j = 0;
    }
    {
#line 434
    while (1) {
      while_continue___0: /* CIL Label */ ;

#line 434
      if (! (j < (int )corr_coef_num[(int )corr[i].type])) {
#line 434
        goto while_break___0;
      }
      {
#line 435
      printf((char const   */* __restrict  */)",%d", corr[i].coef[j]);
#line 434
      j ++;
      }
    }
    while_break___2: /* CIL Label */ ;
    }
    while_break___0: 
#line 432
    i ++;
  }
  while_break___1: /* CIL Label */ ;
  }
  while_break: 
  {
#line 437
  printf((char const   */* __restrict  */)" %s\n", devicename);
  }
#line 438
  return;
}
}
#line 442 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
void set_mappings(char *p ) 
{ 
  int i ;
  int axes_on_cl ;
  int btns_on_cl ;
  int axis_mapping ;
  int btn_mapping ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  char *__cil_tmp11 ;
  char *__cil_tmp12 ;
  char *__cil_tmp13 ;
  char *__cil_tmp14 ;
  char *__cil_tmp15 ;
  char *__cil_tmp16 ;
  char *__cil_tmp17 ;
  char *__cil_tmp18 ;
  char *__cil_tmp19 ;
  char *__cil_tmp20 ;
  char *__cil_tmp21 ;
  char *__cil_tmp22 ;
  char *__cil_tmp23 ;
  char *__cil_tmp24 ;
  char *__cil_tmp25 ;
  char *__cil_tmp26 ;
  char *__cil_tmp27 ;
  char *__cil_tmp28 ;
  char *__cil_tmp29 ;
  char *__cil_tmp30 ;
  char *__cil_tmp31 ;

  {
  {
#line 445
  axes_on_cl = 0;
#line 446
  btns_on_cl = 0;
#line 447
  axis_mapping = 0;
#line 448
  btn_mapping = 0;
#line 450
  tmp = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 17U) | (sizeof(__u8 ) << 16),
              & axes);
  }
#line 450
  if (tmp < 0) {
    {
#line 451
    perror("jscal: error getting axes");
#line 452
    exit(1);
    }
  }
  {
#line 454
  tmp___0 = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 18U) | (sizeof(__u8 ) << 16),
                  & buttons);
  }
#line 454
  if (tmp___0 < 0) {
    {
#line 455
    perror("jscal: error getting buttons");
#line 456
    exit(1);
    }
  }
#line 459
  if ((int )axes > 64) {
#line 459
    axes = (char)64;
  }
#line 461
  if (! p) {
    {
#line 462
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: missing argument for --set-mappings\n");
#line 463
    exit(1);
    }
  }
  {
#line 467
  sscanf((char const   */* __restrict  */)((char const   *)p), (char const   */* __restrict  */)"%d",
         & axes_on_cl);
#line 468
  p = strstr((char const   *)p, ",");
  }
#line 470
  if (axes_on_cl != (int )axes) {
    {
#line 471
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: joystick has %d axes and not %d as specified on command line\n",
            (int )axes, axes_on_cl);
#line 473
    exit(1);
    }
  }
#line 477
  i = 0;
  {
#line 477
  while (1) {
    while_continue: /* CIL Label */ ;

#line 477
    if (! (i < (int )axes)) {
#line 477
      goto while_break;
    }
#line 479
    if (! p) {
      {
#line 480
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: missing mapping for axis %d\n",
              i);
#line 481
      exit(1);
      }
    }
    {
#line 483
    p ++;
#line 483
    sscanf((char const   */* __restrict  */)((char const   *)p), (char const   */* __restrict  */)"%d",
           & axis_mapping);
#line 484
    p = strstr((char const   *)p, ",");
    }
#line 487
    if (axis_mapping > 64) {
      {
#line 488
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: invalid axis mapping for axis %d (max is %d)\n",
              i, 64);
#line 489
      exit(1);
      }
    }
#line 491
    axmap[i] = (__u8 )axis_mapping;
#line 477
    i ++;
  }
  while_break___1: /* CIL Label */ ;
  }
  while_break: 
  {
#line 495
  p ++;
#line 495
  sscanf((char const   */* __restrict  */)((char const   *)p), (char const   */* __restrict  */)"%d",
         & btns_on_cl);
#line 496
  p = strstr((char const   *)p, ",");
  }
#line 498
  if (btns_on_cl != (int )buttons) {
#line 498
    if (btns_on_cl != 0) {
      {
#line 499
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: joystick has %d buttons and not %d as specified on command line\n",
              (int )buttons, btns_on_cl);
#line 501
      exit(1);
      }
    }
  }
#line 505
  i = 0;
  {
#line 505
  while (1) {
    while_continue___0: /* CIL Label */ ;

#line 505
    if (! (i < btns_on_cl)) {
#line 505
      goto while_break___0;
    }
#line 507
    if (! p) {
      {
#line 508
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: missing mapping for button %d\n",
              i);
#line 509
      exit(1);
      }
    }
    {
#line 511
    p ++;
#line 511
    sscanf((char const   */* __restrict  */)((char const   *)p), (char const   */* __restrict  */)"%d",
           & btn_mapping);
#line 512
    p = strstr((char const   *)p, ",");
    }
#line 515
    if (btn_mapping > 767) {
      {
#line 516
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: invalid button mapping for button %d (max is %d)\n",
              i, 767);
#line 517
      exit(1);
      }
    }
#line 519
    if (btn_mapping < 256) {
      {
#line 520
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: invalid button mapping for button %d (min is %d)\n",
              i, 256);
#line 521
      exit(1);
      }
    }
#line 523
    buttonmap[i] = (__u16 )btn_mapping;
#line 505
    i ++;
  }
  while_break___2: /* CIL Label */ ;
  }
  while_break___0: ;
#line 526
  if (p) {
    {
#line 527
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: too many values\n");
#line 528
    exit(1);
    }
  }
  {
#line 532
  get_axmap2();
#line 535
  tmp___1 = ioctl(fd, (unsigned long )(((1U << 30) | (unsigned int )(106 << 8)) | 49U) | (sizeof(__u8 [64]) << 16),
                  & axmap);
  }
#line 535
  if (tmp___1 < 0) {
    {
#line 536
    perror("jscal: error setting axis map");
#line 537
    exit(1);
    }
  }
  {
#line 541
  correct_axes();
  }
#line 543
  if (btns_on_cl != 0) {
    {
#line 544
    tmp___2 = ioctl(fd, (unsigned long )(((1U << 30) | (unsigned int )(106 << 8)) | 51U) | (sizeof(__u16 [512]) << 16),
                    & buttonmap);
    }
#line 544
    if (tmp___2 < 0) {
      {
#line 545
      perror("jscal: error setting button map");
#line 546
      exit(1);
      }
    }
  }
#line 549
  return;
}
}
#line 551 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
void set_correction(char *p ) 
{ 
  int i ;
  int j ;
  int t ;
  int tmp ;
  int tmp___0 ;
  char *__cil_tmp7 ;
  char *__cil_tmp8 ;
  char *__cil_tmp9 ;
  char *__cil_tmp10 ;
  char *__cil_tmp11 ;
  char *__cil_tmp12 ;
  char *__cil_tmp13 ;
  char *__cil_tmp14 ;
  char *__cil_tmp15 ;
  char *__cil_tmp16 ;
  char *__cil_tmp17 ;
  char *__cil_tmp18 ;
  char *__cil_tmp19 ;
  char *__cil_tmp20 ;
  char *__cil_tmp21 ;
  char *__cil_tmp22 ;
  char *__cil_tmp23 ;

  {
  {
#line 554
  t = 0;
#line 556
  tmp = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 17U) | (sizeof(__u8 ) << 16),
              & axes);
  }
#line 556
  if (tmp < 0) {
    {
#line 557
    perror("jscal: error getting axes");
#line 558
    exit(1);
    }
  }
#line 561
  if ((int )axes > 64) {
#line 561
    axes = (char)64;
  }
#line 563
  if (! p) {
    {
#line 564
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: missing number of axes\n");
#line 565
    exit(1);
    }
  }
  {
#line 567
  sscanf((char const   */* __restrict  */)((char const   *)p), (char const   */* __restrict  */)"%d",
         & t);
#line 568
  p = strstr((char const   *)p, ",");
  }
#line 570
  if (t != (int )axes) {
    {
#line 571
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: joystick has different number of axes (%d) than specified in command line (%d)\n",
            (int )axes, t);
#line 573
    exit(1);
    }
  }
#line 577
  i = 0;
  {
#line 577
  while (1) {
    while_continue: /* CIL Label */ ;

#line 577
    if (! (i < (int )axes)) {
#line 577
      goto while_break;
    }
#line 579
    if (! p) {
      {
#line 580
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: missing correction type for axis %d\n",
              i);
#line 581
      exit(1);
      }
    }
    {
#line 583
    p ++;
#line 583
    sscanf((char const   */* __restrict  */)((char const   *)p), (char const   */* __restrict  */)"%d",
           & t);
#line 584
    p = strstr((char const   *)p, ",");
    }
#line 587
    if (t > 1) {
      {
#line 588
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: unknown correction type for axis %d\n",
              i);
#line 589
      exit(1);
      }
    }
#line 591
    corr[i].type = (__u16 )t;
#line 593
    if (! p) {
      {
#line 594
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: missing precision for axis %d\n",
              i);
#line 595
      exit(1);
      }
    }
    {
#line 597
    p ++;
#line 597
    sscanf((char const   */* __restrict  */)((char const   *)p), (char const   */* __restrict  */)"%d",
           & t);
#line 598
    p = strstr((char const   *)p, ",");
#line 600
    corr[i].prec = (__s16 )t;
#line 602
    j = 0;
    }
    {
#line 602
    while (1) {
      while_continue___0: /* CIL Label */ ;

#line 602
      if (! (j < (int )corr_coef_num[corr[i].type])) {
#line 602
        goto while_break___0;
      }
#line 603
      if (! p) {
        {
#line 604
        fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: missing coefficient %d for axis %d\n",
                j, i);
#line 605
        exit(1);
        }
      }
      {
#line 607
      p ++;
#line 607
      sscanf((char const   */* __restrict  */)((char const   *)p), (char const   */* __restrict  */)"%d",
             & corr[i].coef[j]);
#line 608
      p = strstr((char const   *)p, ",");
#line 602
      j ++;
      }
    }
    while_break___2: /* CIL Label */ ;
    }
    while_break___0: 
#line 577
    i ++;
  }
  while_break___1: /* CIL Label */ ;
  }
  while_break: ;
#line 612
  if (p) {
    {
#line 613
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: too many values\n");
#line 614
    exit(1);
    }
  }
  {
#line 617
  tmp___0 = ioctl(fd, (unsigned long )(((1U << 30) | (unsigned int )(106 << 8)) | 33U) | (sizeof(struct js_corr ) << 16),
                  & corr);
  }
#line 617
  if (tmp___0 < 0) {
    {
#line 618
    perror("jscal: error setting correction");
#line 619
    exit(1);
    }
  }
#line 621
  return;
}
}
#line 623 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
void test_center(void) 
{ 
  int i ;
  struct js_event ev ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  ssize_t tmp___2 ;
  char *__cil_tmp7 ;
  char *__cil_tmp8 ;
  char *__cil_tmp9 ;
  char *__cil_tmp10 ;
  char *__cil_tmp11 ;

  {
  {
#line 628
  tmp = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 17U) | (sizeof(__u8 ) << 16),
              & axes);
  }
#line 628
  if (tmp < 0) {
    {
#line 629
    perror("jscal: error getting axes");
#line 630
    exit(1);
    }
  }
  {
#line 633
  tmp___0 = ioctl(fd, (unsigned long )(((2U << 30) | (unsigned int )(106 << 8)) | 18U) | (sizeof(__u8 ) << 16),
                  & buttons);
  }
#line 633
  if (tmp___0 < 0) {
    {
#line 634
    perror("jscal: error getting buttons");
#line 635
    exit(1);
    }
  }
  {
#line 638
  tmp___1 = fcntl(fd, 4, 2048);
  }
#line 638
  if (tmp___1) {
    {
#line 639
    perror("jscal: cannot set nonblocking mode");
#line 640
    exit(1);
    }
  }
  {
#line 643
  while (1) {
    while_continue: /* CIL Label */ ;
    {
#line 643
    tmp___2 = read(fd, (void *)(& ev), sizeof(struct js_event ));
    }
#line 643
    if (! ((unsigned long )tmp___2 == sizeof(struct js_event ))) {
#line 643
      goto while_break;
    }
#line 645
    if (((int )ev.type & -129) == 2) {
#line 645
      goto case_2;
    }
#line 647
    if (((int )ev.type & -129) == 1) {
#line 647
      goto case_1;
    }
#line 644
    goto switch_break;
    case_2: 
#line 646
    js.axis[ev.number] = (int )ev.value;
#line 646
    goto switch_break;
    case_1: 
#line 648
    js.buttons = (js.buttons & ~ (1 << (int )ev.number)) | ((int )ev.value << (int )ev.number);
    switch_break: ;
  }
  while_break___1: /* CIL Label */ ;
  }
  while_break: 
#line 652
  i = 0;
  {
#line 652
  while (1) {
    while_continue___0: /* CIL Label */ ;

#line 652
    if (! (i < (int )axes)) {
#line 652
      goto while_break___0;
    }
#line 652
    if (js.axis[i]) {
      {
#line 653
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: axes not calibrated\n");
#line 654
      exit(2);
      }
    }
#line 652
    i ++;
  }
  while_break___2: /* CIL Label */ ;
  }
  while_break___0: ;
#line 656
  if (js.buttons) {
    {
#line 657
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"jscal: buttons pressed\n");
#line 658
    exit(3);
    }
  }
#line 660
  return;
}
}
#line 662 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jscal.c"
int action  =    0;
#line 51 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jstest.c"
char *axis_names[64]  = 
#line 51 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jstest.c"
  {      (char *)"X",      (char *)"Y",      (char *)"Z",      (char *)"Rx", 
        (char *)"Ry",      (char *)"Rz",      (char *)"Throttle",      (char *)"Rudder", 
        (char *)"Wheel",      (char *)"Gas",      (char *)"Brake",      (char *)"?", 
        (char *)"?",      (char *)"?",      (char *)"?",      (char *)"?", 
        (char *)"Hat0X",      (char *)"Hat0Y",      (char *)"Hat1X",      (char *)"Hat1Y", 
        (char *)"Hat2X",      (char *)"Hat2Y",      (char *)"Hat3X",      (char *)"Hat3Y", 
        (char *)"?",      (char *)"?",      (char *)"?",      (char *)"?", 
        (char *)"?",      (char *)"?",      (char *)"?"};
#line 58 "/home/june/repo/benchmarks/collector/temp/joystick-1.4.7/utils/jstest.c"
char *button_names[512]  = 
#line 58
  {      (char *)"Btn0",      (char *)"Btn1",      (char *)"Btn2",      (char *)"Btn3", 
        (char *)"Btn4",      (char *)"Btn5",      (char *)"Btn6",      (char *)"Btn7", 
        (char *)"Btn8",      (char *)"Btn9",      (char *)"?",      (char *)"?", 
        (char *)"?",      (char *)"?",      (char *)"?",      (char *)"?", 
        (char *)"LeftBtn",      (char *)"RightBtn",      (char *)"MiddleBtn",      (char *)"SideBtn", 
        (char *)"ExtraBtn",      (char *)"ForwardBtn",      (char *)"BackBtn",      (char *)"TaskBtn", 
        (char *)"?",      (char *)"?",      (char *)"?",      (char *)"?", 
        (char *)"?",      (char *)"?",      (char *)"?",      (char *)"?", 
        (char *)"Trigger",      (char *)"ThumbBtn",      (char *)"ThumbBtn2",      (char *)"TopBtn", 
        (char *)"TopBtn2",      (char *)"PinkieBtn",      (char *)"BaseBtn",      (char *)"BaseBtn2", 
        (char *)"BaseBtn3",      (char *)"BaseBtn4",      (char *)"BaseBtn5",      (char *)"BaseBtn6", 
        (char *)"BtnDead",      (char *)"BtnA",      (char *)"BtnB",      (char *)"BtnC", 
        (char *)"BtnX",      (char *)"BtnY",      (char *)"BtnZ",      (char *)"BtnTL", 
        (char *)"BtnTR",      (char *)"BtnTL2",      (char *)"BtnTR2",      (char *)"BtnSelect", 
        (char *)"BtnStart",      (char *)"BtnMode",      (char *)"BtnThumbL",      (char *)"BtnThumbR", 
        (char *)"?",      (char *)"?",      (char *)"?",      (char *)"?", 
        (char *)"?",      (char *)"?",      (char *)"?",      (char *)"?", 
        (char *)"?",      (char *)"?",      (char *)"?",      (char *)"?", 
        (char *)"?",      (char *)"?",      (char *)"?",      (char *)"?", 
        (char *)"?",      (char *)"WheelBtn",      (char *)"Gear up"};
